### ISSUE TITLE
IDL does not compile with new idl compiler. Are IDLs case-sensitive ore case-insensitive?

### ISSUE THREAD

**Issue by gsnuffles** [eclipse-cyclonedds/cyclonedds-cxx#151]
Hi,
when I try to compile the following idl file:
```idl
module Integrationtester
{
  struct Command
  {
    string command;
  };
};
```

I get the error 
`Declaration 'command' collides with earlier an declaration of 'Command'`

This compiled with the "old" [idlpp-cxx-Compiler](https://github.com/ADLINK-IST/idlpp-cxx/). This is not a real problem for me, because I can work around that. But I was asking myself if this is intentional. Is it? 

------------------------------------------------------------------------------------------

Also the error message should be `Declaration 'command' collides with an earlier declaration of 'Command'`. The `"earlier"` is in the wrong position, isn't it?

**Comment by k0ekk0ek** [comment]
Hi @gsnuffles! IDL is case insensitive and using `command` as a member name within a `struct` named `Command` is invalid according to the specification. The new compiler supports `-fcase-sensitive` to allow for member names that differ only in case.

**Comment by gsnuffles** [comment]
Thank you for clearing that up.
