### ISSUE TITLE
Read/Take internally limits max samples to 100

### ISSUE THREAD

**Issue by sumanth-nirmal** [eclipse-cyclonedds/cyclonedds-cxx#171]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Cyclone Version**
- cyclonedds - master branch, https://github.com/eclipse-cyclonedds/cyclonedds/commit/c1f7ed4c2bd14542413b24406072c2a8b903f2b0
- cyclonedds-cxx - master branch, https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commit/03c525c3ce309c7308ebb6f22f904f066a18e1e2

**Observed result or behavior:**

When using `read()`/`take()` with unlimited samples, the `read/take` internally wraps the maximum samples to 100 [here](https://github.com/eclipse-cyclonedds/cyclonedds/blob/c1f7ed4c2bd14542413b24406072c2a8b903f2b0/src/core/ddsc/src/dds_read.c#L222), which means regardless of how many samples are available in the reader history cache, it only returns a maximum of 100 samples. The code snippet below should highlight the problem

```cpp
TEST(test, read_unlimited)
{
  constexpr uint32_t depth = 150;
  dds::domain::DomainParticipant dp(0);
  dds::pub::Publisher pub(dp);
  dds::sub::Subscriber sub(dp);
  dds::topic::Topic<DDSType> topic(dp, "test");
  dds::pub::qos::DataWriterQos dw_qos;
  dw_qos.policy(dds::core::policy::History{dds::core::policy::HistoryKind::KEEP_LAST, depth});
  dds::sub::qos::DataReaderQos dr_qos;
  dr_qos.policy(dds::core::policy::History{dds::core::policy::HistoryKind::KEEP_LAST, depth});
  dds::pub::DataWriter<DDSType> dw(pub, topic, dw_qos);
  dds::sub::DataReader<DDSType> dr(sub, topic, dr_qos);

  for (size_t i = 0; i < depth; i++) {
    DDSType msg{};
    msg.sensor_id(111);
    msg.string_bounded(123);
    dw.write(msg);
  }

  std::this_thread::sleep_for(std::chrono::seconds(5));

  auto n_samples = dr.read();
  EXPECT_EQ(n_samples.length(), depth); // expect 150 samples, but only returns 100 samples
}
```

**Expected result or behaviour:**

The `read/take` API shouldn't silently limit the max number of samples when reading.

**Conditions where it occurred / Performed steps:**

This happens when calling the `read()/take()` API and the max samples to read/take is internally limited to 100 here https://github.com/eclipse-cyclonedds/cyclonedds/blob/c1f7ed4c2bd14542413b24406072c2a8b903f2b0/src/core/ddsc/src/dds_read.c#L258

**More details**

This issue arises because the current cyclone C API doesn't support to read/take all the available samples in the reader history cache (this is because of how the API interface works, it expects the users to pass in an array of pointers for the samples). C++ API works around this issue by first locking the reader history cache here https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/03c525c3ce309c7308ebb6f22f904f066a18e1e2/src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp#L171 and gets the number of the samples in the cache, then initializes the buffers to hold this number of samples. Then `dds_readcdr` is called with these initialized buffers but with a special value for the max number of samples `DDS_READ_WITHOUT_LOCK` to indicate that the reader history is already locked here https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/03c525c3ce309c7308ebb6f22f904f066a18e1e2/src/ddscxx/src/org/eclipse/cyclonedds/sub/AnyDataReaderDelegate.cpp#L226. However, we lose the information about the number of samples in the reader history cache when the `dds_readcdr()` is called because of the API signature, and the API internally limits the max samples to read to 100 here https://github.com/eclipse-cyclonedds/cyclonedds/blob/c1f7ed4c2bd14542413b24406072c2a8b903f2b0/src/core/ddsc/src/dds_read.c#L258

Related to issue: https://github.com/eclipse-cyclonedds/cyclonedds/issues/74

**Comment by hansvanthag** [comment]
@eboasson, any update on this issue (as there's now also other users running into this limitation) ?

**Comment by eboasson** [comment]
There is definitely progress, but perhaps of a different kind than one would expect at first:

For a rather long time I was really planning on changing the C API's `dds_read` and `dds_take` functions in a backwards-incompatible way but never quite got around to it (also a reason for not bumping the major version for so long). On studying the work referred to by [this comment](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1437#issuecomment-1271670074), I actually changed my mind.

That means the blocker for *extending* the C API with regards to reading/taking data no longer exists. That in turn means we just need to add some functions for reading/taking data that take a set of callback functions for doing something with the samples to be returned. Then the C++ binding can tie it directly to whatever language features it uses to construct the result of the read/take operations.

The API extension hasn't been done yet, but it has become an independent problem. Solving this particular one problem for once and for all is therefore no longer blocked either. And in my mind, removing an obstacle like that is significant progress 🙂

**Comment by sumanth-nirmal** [comment]
I think this is solved with the following
- https://github.com/eclipse-cyclonedds/cyclonedds/pull/1744
- https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/434

**Comment by sumanth-nirmal** [comment]
I think this is solved with the following
- https://github.com/eclipse-cyclonedds/cyclonedds/pull/1744
- https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/434

**Comment by eboasson** [comment]
@sumanth-nirmal 🙏 You're right, it got solved and I completely forgot to update this ticket.
