### ISSUE TITLE
DataReader listener with StatusMask::all() aborts in on_data_readers

### ISSUE THREAD

**Issue by ichernev** [eclipse-cyclonedds/cyclonedds-cxx#188]
So this might be viewed as a feature as well, but `DataReader.listener(l, StatusMask::all())` leads to an abort inside `on_data_readers` due to `detail::DataReader` not overriding `on_data_readers` virtual method from `EntityDelegate`.

```
ddscxxHelloworldSubscriber: /home/iskren/src/motional/cyclonedds-cxx/src/ddscxx/src/org/eclipse/cyclonedds/core/EntityDelegate.cpp:375: virtual void org::eclipse::cyclonedds::core::EntityDelegate::on_data_readers(dds_entity_t): Assertion `false' failed.
```

I tried to override it in `detail::DataReader` (and also add `on_data_readers` in the `DataReaderListener` interface), then the crash is gone, and the callback is called, but the messages are not received, which suggests that I have to actively "handle" the event in some non-obvious way.

In general, the idea of having both read and write callbacks in the same mask and using `all()` is a bit dangerous. Ideally the `listener(l, mask)` should strip the mask only to a subset of events which makes sense for the particular use case (reader, writer, subscriber, publisher, domain participant) because if the wrong event comes it will crash, because the methods are not overriden, and should not be (because it's not the right place). So having `allFeatures` mask AND-ed to the passed on in each class that supports listeners will make it safer.

```patch
commit b6ea40d6255404ac21a46a2c63a31913c0e3e220
Author: Iskren Chernev <me@iskren.info>
Date:   Thu Dec 9 21:39:34 2021 +0200

    Fix on_data_readers abort

diff --git a/src/ddscxx/include/dds/sub/DataReaderListener.hpp b/src/ddscxx/include/dds/sub/DataReaderListener.hpp
index 497f9ba..eeb5e27 100644
--- a/src/ddscxx/include/dds/sub/DataReaderListener.hpp
+++ b/src/ddscxx/include/dds/sub/DataReaderListener.hpp
@@ -305,6 +305,9 @@ public:
     virtual void on_sample_lost(
         DataReader<T>& reader,
         const dds::core::status::SampleLostStatus& status) = 0;
+
+    /** @copydoc dds::sub::SubscriberListener::on_data_on_readers() */
+    virtual void on_data_readers(DataReader<T>& reader) = 0;
 };
 
 
@@ -364,6 +367,9 @@ public:
     virtual void on_sample_lost(
         DataReader<T>&,
         const dds::core::status::SampleLostStatus&) { }
+
+    virtual void on_data_readers(
+        DataReader<T>&) { }
 /** @endcond */
 };
 
diff --git a/src/ddscxx/include/dds/sub/detail/DataReader.hpp b/src/ddscxx/include/dds/sub/detail/DataReader.hpp
index 622ce7e..1e454bd 100644
--- a/src/ddscxx/include/dds/sub/detail/DataReader.hpp
+++ b/src/ddscxx/include/dds/sub/detail/DataReader.hpp
@@ -125,6 +125,8 @@ public:
     void on_sample_lost(dds_entity_t,
           org::eclipse::cyclonedds::core::SampleLostStatusDelegate &);
 
+    void on_data_readers(dds_entity_t);
+
 private:
     dds::sub::Subscriber sub_;
     dds::sub::status::DataState status_filter_;
diff --git a/src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp b/src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
index e97fdd1..02e4c20 100644
--- a/src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
+++ b/src/ddscxx/include/dds/sub/detail/TDataReaderImpl.hpp
@@ -1439,6 +1439,16 @@ void dds::sub::detail::DataReader<T>::on_sample_lost(dds_entity_t,
     l->on_sample_lost(dr, s);
 }
 
+template <typename T>
+void dds::sub::detail::DataReader<T>::on_data_readers(dds_entity_t)
+{
+    dds::sub::DataReader<T, dds::sub::detail::DataReader> dr = wrapper();
+
+    dds::sub::DataReaderListener<T> *l =
+        reinterpret_cast<dds::sub::DataReaderListener<T> *>(this->listener_get());
+    l->on_data_readers(dr);
+}
+
 // End of implementation
 
 #endif /* CYCLONEDDS_DDS_SUB_TDATAREADER_IMPL_HPP_ */
```

**Comment by k0ekk0ek** [comment]
Hi @ichernev, The `on_data_readers` event is a subscriber event, not a reader event. An exception should probably be thrown when setting/activating the listener(?) The `assert` is likely there to notice the wrong listener being set in debug builds. Of course, I could be wrong about all of this :slightly_smiling_face: @e-hndrks, perhaps you can enlighten us?

**Comment by e-hndrks** [comment]
Hi @ichernev and @k0ekk0ek,

Indeed the on_data_readers event is a Subscriber event (Readers have the data_available event) and so is only meant to be available on the Subscriber and on its Factory, the Participant. So adding it to the DataReaderListener here is not the solution. What is clearly wrong is that if you use the StatusMask::all() on the DataReader it generates an on_data_readers event which then as a consequence to invoke the on_data_readers() operation of the reader. However, the on_data_readers event should never occur on a Reader: period. Therefore I am not sure  whether this is a C++ issue, or whether the issue originates in the C API. I will do some research and get back to you about it.

**Comment by e-hndrks** [comment]
Hi @ichernev,

What exactly do you do to create the problem? I am setting a mask to all() on the ReaderListener and write some samples, but I don't get the data_on_readers event. What kind of action creates your event? Is it possible to post a small reproducer?

**Comment by ichernev** [comment]
> What kind of action creates your event? Is it possible to post a small reproducer?

I use all() on a data reader, yes. I'll need some time to "synthesize" a minimal reproducing code sample, I'll get going :)

**Comment by e-hndrks** [comment]
After consultation with @eboasson I can now say that we both expect that this issue is not caused by the C++ API but by the way events are handled in the Cyclone core. It still would be nice to have a reproducer though, to study its exact root cause and to test our future fix.

**Comment by ichernev** [comment]
OK, so you just need to modify your example to reproduce it:
```patch
diff --git a/examples/helloworld/publisher.cpp b/examples/helloworld/publisher.cpp
index 2a15765..70df8a3 100644
--- a/examples/helloworld/publisher.cpp
+++ b/examples/helloworld/publisher.cpp
@@ -39,33 +39,12 @@ int main() {
         /* Now, the writer can be created to publish a HelloWorld message. */
         dds::pub::DataWriter<HelloWorldData::Msg> writer(publisher, topic);
 
-        /* For this example, we'd like to have a subscriber to actually read
-         * our message. This is not always necessary. Also, the way it is
-         * done here is just to illustrate the easiest way to do so. It isn't
-         * really recommended to do a wait in a polling loop, however.
-         * Please take a look at Listeners and WaitSets for much better
-         * solutions, albeit somewhat more elaborate ones. */
-        std::cout << "=== [Publisher] Waiting for subscriber." << std::endl;
-        while (writer.publication_matched_status().current_count() == 0) {
-            std::this_thread::sleep_for(std::chrono::milliseconds(20));
-        }
-
         /* Create a message to write. */
-        HelloWorldData::Msg msg(1, "Hello World");
-
-        /* Write the message. */
-        std::cout << "=== [Publisher] Write sample." << std::endl;
-        writer.write(msg);
-
-        /* With a normal configuration (see dds::pub::qos::DataWriterQos
-         * for various different writer configurations), deleting a writer will
-         * dispose all its related message.
-         * Wait for the subscriber to have stopped to be sure it received the
-         * message. Again, not normally necessary and not recommended to do
-         * this in a polling loop. */
-        std::cout << "=== [Publisher] Waiting for sample to be accepted." << std::endl;
-        while (writer.publication_matched_status().current_count() > 0) {
-            std::this_thread::sleep_for(std::chrono::milliseconds(50));
+        for (int i = 1;; ++i) {
+            HelloWorldData::Msg msg(i, "Hello World");
+            std::cout << "=== [Publisher] Write sample. " << i << std::endl;
+            writer.write(msg);
+            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
         }
     }
     catch (const dds::core::Exception& e) {
diff --git a/examples/helloworld/subscriber.cpp b/examples/helloworld/subscriber.cpp
index 197a732..d1aafbe 100644
--- a/examples/helloworld/subscriber.cpp
+++ b/examples/helloworld/subscriber.cpp
@@ -39,50 +39,11 @@ int main() {
         /* Now, the reader can be created to subscribe to a HelloWorld message. */
         dds::sub::DataReader<HelloWorldData::Msg> reader(subscriber, topic);
 
-        /* Poll until a message has been read.
-         * It isn't really recommended to do this kind wait in a polling loop.
-         * It's done here just to illustrate the easiest way to get data.
-         * Please take a look at Listeners and WaitSets for much better
-         * solutions, albeit somewhat more elaborate ones. */
-        std::cout << "=== [Subscriber] Wait for message." << std::endl;
-        bool poll = true;
-        while (poll) {
-            /* For this example, the reader will return a set of messages (aka
-             * Samples). There are other ways of getting samples from reader.
-             * See the various read() and take() functions that are present. */
-            dds::sub::LoanedSamples<HelloWorldData::Msg> samples;
+        reader.listener(new dds::sub::NoOpDataReaderListener<HelloWorldData::Msg>(),
+                dds::core::status::StatusMask::all());
 
-            /* Try taking samples from the reader. */
-            samples = reader.take();
-
-            /* Are samples read? */
-            if (samples.length() > 0) {
-                /* Use an iterator to run over the set of samples. */
-                dds::sub::LoanedSamples<HelloWorldData::Msg>::const_iterator sample_iter;
-                for (sample_iter = samples.begin();
-                     sample_iter < samples.end();
-                     ++sample_iter) {
-                    /* Get the message and sample information. */
-                    const HelloWorldData::Msg& msg = sample_iter->data();
-                    const dds::sub::SampleInfo& info = sample_iter->info();
-
-                    /* Sometimes a sample is read, only to indicate a data
-                     * state change (which can be found in the info). If
-                     * that's the case, only the key value of the sample
-                     * is set. The other data parts are not.
-                     * Check if this sample has valid data. */
-                    if (info.valid()) {
-                        std::cout << "=== [Subscriber] Message received:" << std::endl;
-                        std::cout << "    userID  : " << msg.userID() << std::endl;
-                        std::cout << "    Message : \"" << msg.message() << "\"" << std::endl;
-
-                        /* Only 1 message is expected in this example. */
-                        poll = false;
-                    }
-                }
-            } else {
-                std::this_thread::sleep_for(std::chrono::milliseconds(20));
-            }
+        for (;;) {
+            std::this_thread::sleep_for(std::chrono::milliseconds(1000));
         }
     } catch (const dds::core::Exception& e) {
         std::cerr << "=== [Subscriber] DDS exception: " << e.what() << std::endl;
```

To be fair, your build system is a bit weird, I had to add `-DCMAKE_CXX_FLAGS=-pthread`, and then I couldn't find the executables, but I've tested pretty similar code in a sane build environment and it reproduces. If you change `StatusMask::all` to `StatusMask::data_available` it doesn't crash.

**Comment by k0ekk0ek** [comment]
I'll leave the actual listener question for @e-hndrks, he's more knowledgeable in that aread. `-DCMAKE_CXX_FLAGS=-pthread` shouldn't be necessary. If it is, that's an error. Cyclone DDS provides operating system agnostic threading primitives and if POSIX threads are required than that should've been propagated in the CMake flags. Can I ask you to describe your setup a bit? I'd like to ensure that problem doesn't occur in the future.

**Comment by ichernev** [comment]
It might be due to `std::this_thread::sleep_for`.

**Comment by ichernev** [comment]
> Can I ask you to describe your setup a bit?

In order for me to build your sample, I run the cyclonedds-cxx project cmake with `-DCMAKE_PREFIX_PATH=path/to/installed/cyclonedds`, with `-DBUILD_EXAMPLES=On`, `-DCMAKE_CXX_FLAGS=-pthread`, (+ `-B build`) and then after I install whatever was build (`cmake --build build && cmake --install build`), I don't see the examples anywhere...

So I copied the example folder only and build it with separate flags: `-DCycloneDDS_DIR` and `-DCycloneDDS-CXX_DIR` (I couldn't find any other way to build with CMAKE_PREFIX_PATH or anything else), and then that works. For cross compiling it is even harder, I can file an issue at some point :)

**Comment by e-hndrks** [comment]
@ichernev Thanks for the reproducer: it reproduces correctly on my machine too. It seems indeed the issue is under the C++ cover, where the C99 API (that C++ is built on top of) doesn't distinguish between Readers (that according to the DDS spec don't have a on_data_readers callback) and Subscribers (that do). It simply states that if the on_data_readers event is listed in your mask, it is the preferred callback over the on_data_available event. For Subscribers that is indeed the case, but for Readers is should not be. I will discuss with @eboasson what the best approach to tackle this problem is, but for now I would think that the preference for the on_data_readers should only exist for Subscribers and DomainParticipants, not for DataReaders.

**Comment by ichernev** [comment]
Well, an easy way to fix it is to "clamp" the mask in the DataReader to remove the on_data_readers flag (`& ~on_data_readers()`). The C API can be changed separately...

**Comment by k0ekk0ek** [comment]
@ichernev, both *cyclonedds* and *cyclonedds-cxx* require passing `-DBUILD_EXAMPLES=on` to build the examples from the build tree. Building examples (and testing for that matter), is off by default.

If you copy the examples manually, then you need to specify the install path for both *cyclonedds* and *cyclonedds-cxx*, but you shouldn't need to specify `-pthread` manually.  We link the `Threads::Threads` target as *INTERFACE* to *ddsrt*, which is an interface type library. The problem might be that we link *ddsrt* privately to *ddsc* and only copy the definitions and directories into the *ddsc* target (`src/core/CMakeLists.txt` line 56). I'm pretty sure that can be handled differently. Still, strictly speaking the C++ binding shouldn't require linking with POSIX threads directly and I'm pretty sure it builds on the abstractions in *ddsrt* (provided through *ddsc*).

This [stackoverflow post](https://stackoverflow.com/questions/46994982/g-why-do-i-have-to-pass-pthread-option-while-using-stdthread) mentions the same problem. We should probably test if GCC is being used, and if so, depend on `Threads::Threads` for the example too. Either that, or we change the sleep function being used.

Cross compiling shouldn't be harder. If you provide a proper toolchain file everything works mostly the same right? I will acknowledge that cross compiling with two different projects isn't super straightforward in CMake though :slightly_smiling_face: Of course, if you have pointers on how to improve user-friendliness, that's very welcome :+1:

**Comment by e-hndrks** [comment]
Hi @ichernev , as you can see, I created the following pull-request https://github.com/eclipse-cyclonedds/cyclonedds/pull/1076 to fix the root cause of this issue in the C99 API of CycloneDDS. No further fixes are needed on the C++ API. Hope that solves all your C++ issues as well?

**Comment by ichernev** [comment]
OK, I can verify that this fix indeed fixes the `abort` that was happening before! Thank you @eboasson!
