### ISSUE TITLE
How to read builtin topic data

### ISSUE THREAD

**Issue by skysky97** [eclipse-cyclonedds/cyclonedds-cxx#198]
I have found the API `dds::sub::builtin_subscriber`，but it says not supported yet.

**Comment by eboasson** [comment]
Yes, that's (unfortunately) correct. There is an implementation (https://github.com/eclipse-cyclonedds/cyclonedds-cxx/pull/135) but that has to play such dirty tricks to work around some limitations of the C API that we decided we must fix the C API and redo it. But it does work.

So if you need it now, merging that PR is the way to go.
