### ISSUE TITLE
Problem compiling the master branch

### ISSUE THREAD

**Issue by iliak88** [eclipse-cyclonedds/cyclonedds-cxx#244]
Hi,
I'm using ubuntu 18.04.3 LTS.
I just cloned the project and tried to build using the instructions written in the readme file but I'm getting these errors:

> robil@apollo:~/cyclonedds-cxx/build$ cmake --build . --target install

> Scanning dependencies of target idlcxx
> [  1%] Building C object src/idlcxx/CMakeFiles/idlcxx.dir/src/types.c.o
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c: In function ‘emit_member’:
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c:43:47: error: ‘idl_member_t {aka const struct idl_member}’ has no member named ‘try_construct’
>    if (((const idl_member_t *)idl_parent(node))->try_construct.annotation != NULL) {
>                                                ^~
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c:44:25: error: ‘IDL_WARN_UNSUPPORTED_ANNOTATIONS’ undeclared (first use in this function); did you mean ‘IDL_PARSE_ANNOTATION’?
>      idl_warning(pstate, IDL_WARN_UNSUPPORTED_ANNOTATIONS, idl_location(node),
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                          IDL_PARSE_ANNOTATION
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c:44:25: note: each undeclared identifier is reported only once for each function it appears in
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c: In function ‘emit_enum’:
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c:370:25: error: ‘IDL_WARN_UNSUPPORTED_ANNOTATIONS’ undeclared (first use in this function); did you mean ‘IDL_PARSE_ANNOTATION’?
>      idl_warning(pstate, IDL_WARN_UNSUPPORTED_ANNOTATIONS, idl_location(node), "The @default_literal annotation is not fully supported yet in the C++ generator and will not modify default construction behaviour");
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                          IDL_PARSE_ANNOTATION
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c: In function ‘emit_case’:
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c:559:33: error: ‘idl_case_t {aka const struct idl_case}’ has no member named ‘try_construct’
>    if (((const idl_case_t *)node)->try_construct.annotation != NULL) {
>                                  ^~
> /home/robil/cyclonedds-cxx/src/idlcxx/src/types.c:560:25: error: ‘IDL_WARN_UNSUPPORTED_ANNOTATIONS’ undeclared (first use in this function); did you mean ‘IDL_PARSE_ANNOTATION’?
>      idl_warning(pstate, IDL_WARN_UNSUPPORTED_ANNOTATIONS, idl_location(node),
>                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>                          IDL_PARSE_ANNOTATION
> src/idlcxx/CMakeFiles/idlcxx.dir/build.make:62: recipe for target 'src/idlcxx/CMakeFiles/idlcxx.dir/src/types.c.o' failed
> make[2]: *** [src/idlcxx/CMakeFiles/idlcxx.dir/src/types.c.o] Error 1
> CMakeFiles/Makefile2:106: recipe for target 'src/idlcxx/CMakeFiles/idlcxx.dir/all' failed
> make[1]: *** [src/idlcxx/CMakeFiles/idlcxx.dir/all] Error 2
> Makefile:151: recipe for target 'all' failed
> make: *** [all] Error 2

I tried looking for idl_member_t and IDL_WARN_UNSUPPORTED_ANNOTATIONS in the project, but can't find it anywhere, is there a step missing in the guide?

**Comment by eboasson** [comment]
That looks like you might be using mismatching versions of `cyclonedds` and `cyclonedds-cxx` — there have been a few changes especially in the `try_construct` bit very recently, so that does seem plausible. Just to be sure, I cloned both repositories and built them without a problem:
```
for x in cyclonedds cyclonedds-cxx ; do
  (git clone https://github.com/eclipse-cyclonedds/$x --branch releases/0.9.x && cd $x && \
      cmake -Bbuild -DCMAKE_INSTALL_PREFIX=/some/where -DCMAKE_PREFIX_PATH=/some/where . && \
      cmake --build build --target install -j 4)
done
```
(Naturally the `/some/where` is where I decided to temporarily install it, you probably would want to use another location.)

Could you please check you have matching versions?

**Comment by iliak88** [comment]
Hi, eboasson!
Thank you for replying.
I tried running your script and got some errors, mainly the -j argument was no recognized.

``````
Cloning into 'cyclonedds'...
remote: Enumerating objects: 29123, done.
remote: Counting objects: 100% (268/268), done.
remote: Compressing objects: 100% (167/167), done.
remote: Total 29123 (delta 141), reused 145 (delta 97), pack-reused 28855
Receiving objects: 100% (29123/29123), 16.43 MiB | 3.60 MiB/s, done.
Resolving deltas: 100% (19417/19417), done.
-- The C compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- The CXX compiler identification is GNU 7.5.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Setting build type to 'RelWithDebInfo' as none was specified.
-- Looking for getopt.h
-- Looking for getopt.h - found
-- Building with OpenSSL support
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of intmax_t
-- Check size of intmax_t - done
-- Looking for stpcpy
-- Looking for stpcpy - found
-- Looking for strlcpy
-- Looking for strlcpy - not found
-- Looking for strlcat
-- Looking for strlcat - not found
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Looking for gethostname
-- Looking for gethostname - found
-- Looking for inet_ntop
-- Looking for inet_ntop - found
-- Looking for inet_pton
-- Looking for inet_pton - found
-- Looking for getaddrinfo
-- Looking for getaddrinfo - found
-- Looking for gethostbyname_r
-- Looking for gethostbyname_r - found
-- Check size of struct sockaddr_in6
-- Check size of struct sockaddr_in6 - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Looking for clock_gettime in c
-- Looking for clock_gettime in c - found
You have called ADD_LIBRARY for library ddsrt-internal without any source files. This typically indicates a problem with your CMakeLists.txt file
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robil/ilia/cyclonedds
Unknown argument -j
Unknown argument 4
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
Cloning into 'cyclonedds-cxx'...
remote: Enumerating objects: 5583, done.
remote: Counting objects: 100% (1958/1958), done.
remote: Compressing objects: 100% (771/771), done.
remote: Total 5583 (delta 1320), reused 1431 (delta 1090), pack-reused 3625
Receiving objects: 100% (5583/5583), 1.53 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (3382/3382), done.
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
-- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR
-- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/robil/ilia/cyclonedds-cxx
Unknown argument -j
Unknown argument 4
Usage: cmake --build <dir> [options] [-- [native-options]]
Options:
  <dir>          = Project binary directory to be built.
  --target <tgt> = Build <tgt> instead of default targets.
                   May only be specified once.
  --config <cfg> = For multi-configuration tools, choose <cfg>.
  --clean-first  = Build target 'clean' first, then build.
                   (To clean only, use --target 'clean'.)
  --use-stderr   = Ignored.  Behavior is default in CMake >= 3.0.
  --             = Pass remaining options to the native tool.
``````

So I tried manually creating build directory and running the installation but it did not work as well:

````
robil@apollo:~/ilia/cyclonedds$ cmake --build build --target install
Error: could not load cache
````

**Comment by eboasson** [comment]
Perhaps I have used some command-line options of CMake that are too new 🤔 I don't know for sure.

Alternatively, you could do:
```
(git clone https://github.com/eclipse-cyclonedds/cyclonedds --branch releases/0.9.x && cd cyclonedds && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/some/where -DCMAKE_PREFIX_PATH=/some/where .. && make install)
(git clone https://github.com/eclipse-cyclonedds/cyclonedds-cxx --branch releases/0.9.x && cd cyclonedds-cxx && mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=/some/where -DCMAKE_PREFIX_PATH=/some/where .. && make install)
```
What I suggested is just a shorthand form, really, with the `-j 4` there to speed up the build process a bit by parallelizing things. I think this avoids all fancy things ...

**Comment by iliak88** [comment]
Thank you, this solution seems to work.

I had to delete libcycloneddsidl.so* files from /usr/local/lib folder - probably from my previous installation, because they were clashing with the new. But after that the installation was successful.

**Comment by eboasson** [comment]
Happy to hear that!
