### ISSUE TITLE
Topic Name Rules

### ISSUE THREAD

**Issue by NoeSechet** [eclipse-cyclonedds/cyclonedds-cxx#250]
Hi! 

I am writing this issue after encountering errors regarding the naming of a Topic

In the previous DDS libraries that I was using I could name my topics with colon characters inside. ie: the ":" character

But after some debugging I figured those colons would make my application throw as follow: 

```bash
Exception in run_example(): Error Bad Parameter - Could not create topic.
===============================================================================
Context     : dds::topic::detail::Topic<T>::Topic
Node        : UnknownNode
```

I also tried with some other characters and it would throw the same error. "*", "-"

When I remove those characters from the names, my application works as expected.

Is it intended like so? Is there a place where I can find the rules regarding the naming of a topic with Cyclone? 

Thank you for your work! :)

**Comment by EttoreVidotto** [comment]
Hi @NoeSechet 
I asked a similar [question](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/194) some time ago. It should be helpful for you too.
Bests,
Ettore
