### ISSUE TITLE
how to read/write messages to file logs

### ISSUE THREAD

**Issue by ghorn** [eclipse-cyclonedds/cyclonedds-cxx#251]
I'm new to DDS so apologies if this is a dumb question. I'm trying to figure out how I can stream messages to a log file, for later reading. I've got a basic understanding of the DCPS model, I've read the OML spec in all it's glory, understand how to send and receive all the messages I could ever need, but have not seen anything about logging messages to disk. 

The only way I have figured out would be to create a Subscriber and DataReader to read a stream of incoming messages, then write each message to a `basic_cdr_stream` to serialize it to bytes, and then write those bytes to a file (with a header before each one for bookkeeping). To retrieve them I would open the file, read in the bytes one chunk at a time, and use the `basic_cdr_stream` to deserialize them back to structs.

Is this a reasonable approach, or am I missing something obvious? Are there any batteries-included message logging mechanisms?

**Comment by ghorn** [comment]
If anyone can like example code that serializes a stream of DDS messages to a file, I would really benefit from it. Any pointers at all would be greatly appreciated. Thanks in advance.

**Comment by ghorn** [comment]
In case it might help someone out, here is (roughly) what I've got so far:
```c++
template <typename T>
void WriteSomeMessagesToFile(const std::vector<T> &samples) {
  // set up serialization machinery
  constexpr int32_t kInitialSerializationBufferSize = 1024;
  std::vector<uint8_t> serialization_buffer(kInitialSerializationBufferSize);
  xcdr_v2_stream cdr_stream(endianness::little_endian);

  // open output file  
  std::ofstream file_stream;
  file_stream.exceptions(std::ios::failbit | std::ios::badbit);
  file_stream.open(filename, std::ios::out | std::ios::binary);

  // write messages to file  
  for (const T& sample : samples) {
    // Serialize next message to bytes
    // TODO(greg): resize serialization_buffer if necessary before serializing!
    cdr_stream.set_buffer(serialization_buffer.data(), serialization_buffer.size());
    write(cdr_stream, sample, false);

    // write message size to log as int64_t
    const auto msg_size = static_cast<std::streamsize>(cdr_stream.position());
    file_stream.write(reinterpret_cast<const char*>(&msg_size), sizeof(msg_size));

    // write serialized message to log
    file_stream.write(reinterpret_cast<char*>(serialization_buffer.data()), msg_size);
  }
}
```

**Comment by eboasson** [comment]
Hi @ghorn I completely missed your originally question, I am so sorry.

Regarding the number of bytes needed, the C++ binding internally uses `get_serialized_size`, which maps to a function generated along with the `write` call you found for actually serializing the data:
```C++
template<typename S, std::enable_if_t<std::is_base_of<cdr_stream, S>::value, bool> = true >
bool move(S& str, const ::U& instance, bool as_key) {
  auto props = get_type_props<::U>();
  str.set_mode(cdr_stream::stream_mode::move, as_key);
  return move(str, instance, props); 
}
```
It seems to me that if you have everything set up so that `write` works for serializing, this `move` operation should work for computing the required size.

(All assuming I am not mistaken. @reicheratwork please correct me if I am!)

**Comment by reicheratwork** [comment]
@eboasson : you are correct in this, you use the generated `move` function to do a "pseudo-write" operation which just moves the cursor in the streamer by the amount it would when writing, but no information is copied from `instance` to the stream.
After the `move` function has returned succesfully (`true` of course), then you can get the cursor position by calling the `position()` function on the streamer used.

It is important that you use the correct type of streamer when doing the streaming operations, as these determine the streaming methods used and therefore the data layout in the stream.
You MUST use the same type of streamer when reading a stream which you have saved, both version and endianness, otherwise the resulting data will not be correct.

If you are not concerned with performance or size considerations, just use an `xcdr_v2_stream` as this will have no issues with IDL features which the "basic" streamer does not support (optionals, extensibilities other than `final`). Otherwise you will need to check which IDL features you want to use, and you might be able to use a `basic_cdr_stream`.

Taking this into consideration, you should get the correct results using the following version of your code:
```
template <typename T>
void WriteSomeMessagesToFile(const std::vector<T> &samples) {
  // set up serialization machinery
  constexpr int32_t kInitialSerializationBufferSize = 1024;
  std::vector<uint8_t> serialization_buffer(kInitialSerializationBufferSize);
  xcdr_v2_stream cdr_stream(endianness::little_endian);

  // open output file  
  std::ofstream file_stream;
  file_stream.exceptions(std::ios::failbit | std::ios::badbit);
  file_stream.open(filename, std::ios::out | std::ios::binary);

  // write messages to file  
  for (const T& sample : samples) {
    // Serialize next message to bytes

    //determine the amount of buffer necessary
    move(cdr_stream, sample, false);

   //resize the buffer to have the required capacity
   serialization_buffer.resize(cdr_stream.position());

    //write to the buffer
    cdr_stream.set_buffer(serialization_buffer.data(), serialization_buffer.size());
    write(cdr_stream, sample, false);

    // write message size to log as int64_t
    const auto msg_size = static_cast<std::streamsize>(cdr_stream.position());
    file_stream.write(reinterpret_cast<const char*>(&msg_size), sizeof(msg_size));

    // write serialized message to log
    file_stream.write(reinterpret_cast<char*>(serialization_buffer.data()), msg_size);
  }
}
```

**Comment by ghorn** [comment]
I'm successfully serializing these messages in C++ and deserializing them in python (see https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/79 for the loading side of things).

I have one question - in the python deserialization, a 4-byte header is expected. I believe it is supposed to have the CDR type. How do I also write that before each sample?

**Comment by thijsmie** [comment]
The four byte header is really for on the wire, to describe which CDR version/Endianness you are using. That you have to specify it in Python and it is not a property of the bytestream is a "historical artifact". I recommend you "just fix it on the python end" by specifying `has_header=False, use_version_2=True/False, endianness=Endianness.Little` in your deserialize calls.

**Comment by reicheratwork** [comment]
> I'm successfully serializing these messages in C++ and deserializing them in python (see [eclipse-cyclonedds/cyclonedds-python#79](https://github.com/eclipse-cyclonedds/cyclonedds-python/issues/79) for the loading side of things).
> 
> I have one question - in the python deserialization, a 4-byte header is expected. I believe it is supposed to have the CDR type. How do I also write that before each sample?

The reason that the streaming function does not generate the header is that the 4-byte header is not just a result of the message data, but also of the QoS setting of the writer.
The QoS setting influences the CDR streaming mode, which is in then written to the header.

One thing that you can do is look at the `write_header` and `finish_header` function in the file `datatopic.hpp` and duplicate their functionality in your code.
The correct order is:
- select the type of streamer to use (`basic_cdr`, `xcdr_v1`, `xcdr_v2`)
- call `move` with the streamer and the message to determine the required buffer size for the serialized message 
- create a buffer with the required size + 4 (for the header)
- call the correct `write_header` copy to set the stream version, endianness, ... fields in the header
- set the buffer for the streamer at 4 bytes offset (to avoid serializing over the header)
- call `write` to serialize the message contents to the stream with the streamer
- call the correct `finish_header` copy to set the stream length field

**Comment by pinakigupta** [comment]
> @eboasson : you are correct in this, you use the generated `move` function to do a "pseudo-write" operation which just moves the cursor in the streamer by the amount it would when writing, but no information is copied from `instance` to the stream. After the `move` function has returned succesfully (`true` of course), then you can get the cursor position by calling the `position()` function on the streamer used.
> 
> It is important that you use the correct type of streamer when doing the streaming operations, as these determine the streaming methods used and therefore the data layout in the stream. You MUST use the same type of streamer when reading a stream which you have saved, both version and endianness, otherwise the resulting data will not be correct.
> 
> If you are not concerned with performance or size considerations, just use an `xcdr_v2_stream` as this will have no issues with IDL features which the "basic" streamer does not support (optionals, extensibilities other than `final`). Otherwise you will need to check which IDL features you want to use, and you might be able to use a `basic_cdr_stream`.
> 
> Taking this into consideration, you should get the correct results using the following version of your code:
> 
> ```
> template <typename T>
> void WriteSomeMessagesToFile(const std::vector<T> &samples) {
>   // set up serialization machinery
>   constexpr int32_t kInitialSerializationBufferSize = 1024;
>   std::vector<uint8_t> serialization_buffer(kInitialSerializationBufferSize);
>   xcdr_v2_stream cdr_stream(endianness::little_endian);
> 
>   // open output file  
>   std::ofstream file_stream;
>   file_stream.exceptions(std::ios::failbit | std::ios::badbit);
>   file_stream.open(filename, std::ios::out | std::ios::binary);
> 
>   // write messages to file  
>   for (const T& sample : samples) {
>     // Serialize next message to bytes
> 
>     //determine the amount of buffer necessary
>     move(cdr_stream, sample, false);
> 
>    //resize the buffer to have the required capacity
>    serialization_buffer.resize(cdr_stream.position());
> 
>     //write to the buffer
>     cdr_stream.set_buffer(serialization_buffer.data(), serialization_buffer.size());
>     write(cdr_stream, sample, false);
> 
>     // write message size to log as int64_t
>     const auto msg_size = static_cast<std::streamsize>(cdr_stream.position());
>     file_stream.write(reinterpret_cast<const char*>(&msg_size), sizeof(msg_size));
> 
>     // write serialized message to log
>     file_stream.write(reinterpret_cast<char*>(serialization_buffer.data()), msg_size);
>   }
> }
> ```

Any help on if I am reading this file , how to deserialize effectively ? Especially how to create the stream object from the file ?

**Comment by reicheratwork** [comment]
> Any help on if I am reading this file , how to deserialize effectively ? Especially how to create the stream object from the file ?

@pinakigupta Which stream object are you talking about, the streamer or the streamed samples?

If you mean the streamer type, it is a `xcdr_v2_stream` since that is the same streamer used when serializing the data.

@ghorn This may also be relevant to you:
If you mean reading the samples from the file, you would use the following steps:
- open the file and read in into an appropriate buffer (`std::vector<char>` or just an array of `char` or whatever)
- update the streamer with the current position in the buffer
- read the sample size from the buffer
- read a sample from the buffer
- loop until no more data in the buffer

Now there is a small bug in the writing side of the code I made, looking back at it: the sample size should come _before_ the serialized sample, for obvious reasons. So the write function should become this:

```
template<typename T>
bool WriteSomeMessagesToFile(const std::string &filename, const std::vector<T> &samples) {
    bool success = true;
    xcdr_v2_stream cdr_stream(endianness::little_endian);

    // open output file  
    std::ofstream file_stream;
    file_stream.exceptions(std::ios::failbit | std::ios::badbit);
    file_stream.open(filename, std::ios::out | std::ios::binary);

    for (const auto &sample:samples) {
        //determining the serialized size of the sample
        if (!org::eclipse::cyclonedds::core::cdr::move(cdr_stream, sample, false)) {
            std::cerr << "Move Error.\n";
            success = false;
            break;
        }

        //write the size of the sample to the file
        uint64_t pos = reinterpret_cast<uint64_t>(cdr_stream.position());
        file_stream.write(reinterpret_cast<const char*>(&pos),sizeof(pos));

        //create enough space to serialize in
       std::vector<char> serialization_buffer(cdr_stream.position());
        cdr_stream.set_buffer(serialization_buffer.data(), serialization_buffer.size());

        //serialize the sample into the buffer
        if (!org::eclipse::cyclonedds::core::cdr::write(cdr_stream, sample, false)) {
            std::cerr << "Write Error.\n";
            success = false;
            break;
        }

        //write the buffer to the file
        file_stream.write(reinterpret_cast<char*>(serialization_buffer.data()), serialization_buffer.size());
    }


    file_stream.close();
    return success;
}
```

And the reading should look something like this:
```
template<typename T>
bool ReadSomeMessagesFromFile(const std::string &filename, std::vector<T> &samples) {
    bool success = true;
    std::ifstream file_stream;
    file_stream.exceptions(std::ios::failbit | std::ios::badbit);
    file_stream.open(filename, std::ios::in | std::ios::binary | std::ios::ate);
    xcdr_v2_stream cdr_stream(endianness::little_endian);

    //get the file size
    size_t bytes = file_stream.tellg();
    uint64_t cursize = 0;
    file_stream.clear();
    file_stream.seekg(0);
    while (bytes >= sizeof(cursize)) {
        //read the header
        file_stream.read(reinterpret_cast<char*>(&cursize), sizeof(cursize));
        
        bytes -= sizeof(cursize);

        if (bytes < cursize) {
            std::cerr << "Header size is inconsistent with remaining bytes.\n";
            success = false;
            break;
        }

        //create sample buffer
        std::vector<char> buffer(cursize);
        file_stream.read(const_cast<char*>(buffer.data()), buffer.size());

        cdr_stream.set_buffer(buffer.data(), buffer.size());
        T sample;

        //read sample from buffer
        if (!org::eclipse::cyclonedds::core::cdr::read(cdr_stream, sample, false)) {
            std::cerr << "Sample read error.\n";
            success = false;
            break;
        }
        samples.push_back(sample);
        bytes -= cursize;
    }
    file_stream.close();

    return success;
}
```
