### ISSUE TITLE
IDL: union with case TRUE fails to build

### ISSUE THREAD

**Issue by damiandixon** [eclipse-cyclonedds/cyclonedds-cxx#26]
The following IDL snippet generates code but the code generated fails to build:

```
   union SomeType switch (boolean)
   {
     // the value when present
     case TRUE : long value;
   };
```

The compiler issues the following error:
```
/home/damian/projects/dependencies/cyclone-dds/cyclonedds-cxx/examples/helloworld/build/HelloWorldDataSplDcps.cpp: In function ‘void __HelloWorldData_SomeType__copyIn(const void*, void*)’:
/home/damian/projects/dependencies/cyclone-dds/cyclonedds-cxx/examples/helloworld/build/HelloWorldDataSplDcps.cpp:16:10: error: ‘TRUE’ was not declared in this scope
   16 |     case TRUE:
      |          ^~~~
```
The same IDL snippet generates compilerable code with OpenSplice.

Ubuntu 20.04, g++ 9.3.0

**Comment by eboasson** [comment]
My guess is that this will fix it: https://github.com/ADLINK-IST/idlpp-cxx/pull/5 . On macOS it compiled also with `TRUE` in there — presumably some header file defines it on macOS and not on Linux. I haven't tried it on Linux.

**Comment by damiandixon** [comment]
That fixes this problem for me. Thanks.
