### ISSUE TITLE
Cannot compile nested structures in IDL file

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds-cxx#263]
Hello everyone,
When I try to compile the following IDL file (I simply added a new folder in the _examples_ subfolder and adapted the _helloworld_ example):
```idl
module MySpace{

struct SampleInfo {
	short Time;
};

struct MySample {
	SampleInfo Info;
};

struct MyClass : MySample {
	short Id;
};
#pragma keylist MyClass Id

}; // MySpace

```
the error
```bat
FAILED: examples/nested_idl/my_nested_idl.hpp examples/nested_idl/my_nested_idl.cpp 
```
occurs. If I look at the generated file, this is unexpectedly interrupted:
![Error nested IDL](https://user-images.githubusercontent.com/79527119/162776692-9c0badd5-0824-4323-a1a3-c051eea8e177.PNG)
Am I missing something?

**Used CycloneDDS versions**
* cyclonedds: master branch, eclipse-cyclonedds/cyclonedds@95d0c70bcb2df131f95e4f82d989a235e247c354
* cyclonedds-cxx: master branch, 22b2c2e358dc1acde285894bfeac6a9eabc59d4a

Thank you in advance for your help. Any answer would be appreciated.
Best regards,
Ettore Vidotto

**Comment by eboasson** [comment]
Looks to me like a bug in the C++ backend of IDLC:
```
Assertion failed: (pstate->paths), function generate, file generator.c, line 952.
```

@reicheratwork any chance you can find some time to look into this?

**Comment by reicheratwork** [comment]
looking into it
