### ISSUE TITLE
Not receiving instance state when using multiple (instance) writers 

### ISSUE THREAD

**Issue by kjrusscher** [eclipse-cyclonedds/cyclonedds-cxx#265]
### Situation
The following IDL file is used:
```
module RTP {
    @appendable
    struct Offer {
        @key string videoSourceID;
        string sdp;
    }; 
};
```
Two writers are started on the same topic but they are writing on separate instances; one uses `videoSourceID = "writer 1"`, the other uses `videoSourceID = "writer 2"`.   
There is one reader that does a take on the topic once every second, the code below is looped every second:
```
samplesRTPOffer = rtpOfferReader.take();
for (auto sample = samplesRTPOffer.begin(); sample < samplesRTPOffer.end(); ++sample) {
    dds::sub::status::InstanceState instanceState = sample->info().state().instance_state();
    if (instanceState == dds::sub::status::InstanceState::alive()) {
        // option1
        std::cout << sample->data().videoSourceid() << std::endl;
    } else if ((instanceState & dds::sub::status::InstanceState::not_alive_mask()) != 0) {
        // option2
        std::cout << sample->data().videoSourceid() << std::endl;
    }
}
````
The writers and reader are started in 3 separate applications.
### Problem
First I start the reader application. When I start both writers `option1` (see code above) is called twice. However, when I close both writers `option2` is only called once, when the last running writer application closes. 

What is even stranger to me is that `option2` prints the `videoSourceID` of the writer that started first, so not of the one that stopped last. I did a small test, 4 runs of starting 2 writers then closing them, the results are shown below.
| test # | start    |   start     | stop | stop | which videoSourceID is printed? |
|--|--------------|-----------|------------|-------------|---|
| 1 | writer 1 | writer 2 | writer 1 | writer 2 | writer 1 |
| 2 | writer 1 | writer 2 | writer 2 | writer 1 | writer 1 |
| 3 | writer 2 | writer 1 | writer 1 | writer 2 | writer 2 |
| 4 | writer 2 | writer 1 | writer 2 | writer 1 | writer 2 |

### Question
Is this expected behavior? I would expect to receive from both writers a `not-alive` 'notification'. But if this is expected behavior, I would expect to be notified of the last writer that stops, not the first one that started.

**Comment by kjrusscher** [comment]
I don't know if it matters, but for the topic I'm using the qos:
```
dds::topic::qos::TopicQos topicQos =
    domainParticipant.default_topic_qos() 
    << dds::core::policy::Reliability::Reliable() 
    << dds::core::policy::Durability::TransientLocal();
```

**Comment by reicheratwork** [comment]
Hi @kjrusscher, I will take a look at this issue.

**Comment by reicheratwork** [comment]
Hello @kjrusscher , I think I have found the issue, and will be writing a bug fix.

I will be referencing this issue in the PR for the fix, and if you can test it on your end, that would be much appreciated.

**Comment by kjrusscher** [comment]
Hi @reicheratwork, your commit fixed the problem. It now works very smooth! Thanks!

**Comment by reicheratwork** [comment]
Glad I could be of help @kjrusscher !

I will be making a PR of this commit soon, if you could help reviewing it, then that would be appreciated a lot.

**Comment by kjrusscher** [comment]
@reicheratwork, I will keep an eye out for that commit and I will help reviewing it.
