### ISSUE TITLE
idlcxx on windows exits with -1073741819

### ISSUE THREAD

**Issue by qwerty123443** [eclipse-cyclonedds/cyclonedds-cxx#266]
I'm trying to compile a pretty generic and simple idl file to c++:
```
module OMGTestingData
{
    struct Msg {
        uint32 testID;
        string message;
    };
};
```
compiling it to C using `.\dependencies\install\bin\idlc.exe -W no-implicit-extensibility ..\common\OMGTestingData.idl` works fine
compiling it to C++ using `.\dependencies\install\bin\idlc.exe -W no-implicit-extensibility -l cxx ..\common\OMGTestingData.idl` exits with code -1073741819 (hex 0xC0000005. If you look up this code in Microsoft's documentation [NTSTATUS Values](https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-erref/596a1078-e883-4972-9bbc-49e60bebca55)) you will see that it indicates that the program was terminated due to an access violation)

I've compiled cyclonedds from source (using the latest commit as of writing this) using the following commands:
```
cd cyclonedds
mkdir build
cd build
"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 16 2019" -A x64 "-DCMAKE_INSTALL_PREFIX=../../install" "-DCMAKE_PREFIX_PATH=../../install/" -DCMAKE_BUILD_TYPE=Release ..
"C:\Program Files\CMake\bin\cmake.exe" --build . -j --target ALL_BUILD
"C:\Program Files\CMake\bin\cmake.exe" --build . -j --target INSTALL
exit
```

cyclonedds-cxx was compiled using:
```
cd cyclonedds-cxx
mkdir build
cd build
"C:\Program Files\CMake\bin\cmake.exe" -G "Visual Studio 16 2019" -A x64 "-DCMAKE_INSTALL_PREFIX=../../install" "-DCMAKE_PREFIX_PATH=../../install/" -DBUILD_IDLLIB=ON -DCMAKE_BUILD_TYPE=Release ..
"C:\Program Files\CMake\bin\cmake.exe" --build . -j --target ALL_BUILD
"C:\Program Files\CMake\bin\cmake.exe" --build . -j --target INSTALL
exit
```

I haven't been able to find anyone else that has run into the same issue. Am I doing something dumb?

**Comment by reicheratwork** [comment]
I am looking in to this issue.

**Comment by reicheratwork** [comment]
I am having trouble reproducing this issue with the following commits: CDDS 97a18fc, CDDS-CXX aa9ce49.

Are you on these same commits?
Or could it be that you might have another version of cyclone somewhere in your path?

**Comment by qwerty123443** [comment]
Hmm so I've pulled to the latest commits just now and recompiled everything, and the issue seems to have magically resolved itself. I'll close this issue for now and report back if I manage to reproduce it
