### ISSUE TITLE
Setting up DDS Partitions via .xml or other method

### ISSUE THREAD

**Issue by PenceGL** [eclipse-cyclonedds/cyclonedds-cxx#277]
Hello,

I would like to preface this by saying that I am very new to DDS - this is the first time I've had to work with it as a developer. The current project my company is working on has tasked myself and another developer with implementing DDS in an existing system for transferring messages between two or more instances of that system. We are using CycloneDDS-CXX thus far with a good amount of success.

I wanted to try to set up partitions for the publishers/subscribers. After searching through the code, I found that the `dds::core::QosProvider` class appeared to contain the methods for extracting QoS settings from an .xml file, including partition configuration. I was able to create an instance of a QosProvider and PublisherQos and compile successfully, but every time the build fails with the following linker errors:

```
Undefined symbols for architecture x86_64:
  "org::eclipse::cyclonedds::core::QosProviderDelegate::publisher_qos(char const*)", referenced from:
      dds::core::TQosProvider<org::eclipse::cyclonedds::core::QosProviderDelegate>::publisher_qos() 

  "org::eclipse::cyclonedds::core::QosProviderDelegate::datawriter_qos(char const*)", referenced from:
      dds::core::TQosProvider<org::eclipse::cyclonedds::core::QosProviderDelegate>::datawriter_qos()

  "org::eclipse::cyclonedds::core::QosProviderDelegate::QosProviderDelegate(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)", referenced from:
      dds::core::TQosProvider<org::eclipse::cyclonedds::core::QosProviderDelegate>::TQosProvider(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&)

  "org::eclipse::cyclonedds::core::QosProviderDelegate::~QosProviderDelegate()", referenced from:
      std::__1::default_delete<org::eclipse::cyclonedds::core::QosProviderDelegate>::operator()(org::eclipse::cyclonedds::core::QosProviderDelegate*) const
ld: symbol(s) not found for architecture x86_64
```

My coworker then found what appears to be a discussion in another one of the issues here stating that configuring QoS via .xml is not currently supported by CycloneDDS, despite there being no comment or documentation that we've found so far stating this in the repository.

My questions are:
Is it truly not implemented? And if this is the case, is there another method for establishing partitions that someone could share information about with me? I have seen it hinted at by some RTI documentation that there is a programmatic way to create them, but have not been able to find any example that does not use .xml for configuration.

**Comment by thijsmie** [comment]
Hi @PenceGL,

I saw this just before calling it a night, but I'll give you a quick answer now in case you are currently being blocked by this and revisit this tomorrow.

Indeed, the QoS provider is still on the TODO list. However, you can manually specify QoS policies programmatically upon the creation of an entity. See for example the Publisher QoS object which has your wished for partition policy [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/master/src/ddscxx/include/org/eclipse/cyclonedds/pub/qos/PublisherQosDelegate.hpp) or as used in a test [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/fdbef1f77433cdac9957ab3001f50af6ef42b08e/src/ddscxx/tests/Publisher.cpp#L40).

**Comment by PenceGL** [comment]
@thijsmie Thank you for the response! I never thought to examine those test files as potential sources of guidance.

I don't really understand how to make use of the `PublisherQosDelegate` class in your first link, but I was able to complete a build using the code example from the test file. I assume my partition is enabled at this point...

Do you (or anyone coming across this) happen to know where I can find some guidance on how to extract partition or topic info from incoming data? The examples found by Google search are usually from other DDS implementations and the syntax is just different enough to make it really tough to translate over to CycloneDDS. For example, this question from their forums is something I'd like to accomplish, but I can't figure out how to correctly utilize `ParticipantBuiltinTopicData`.

https://community.rti.com/forum-topic/can-reader-get-partition-sample

**Comment by thijsmie** [comment]
Hi @PenceGL,

You can quickly verify the correctness of your setup by using the `ddsls` tool as provided by the python binding, it will scan your network and print out all information about it (on the master branch we also have a fancy and shiny new `cyclonedds ls` which does the same thing but with fancy colours and better readability).

If you want to extract things at runtime with C++ things are a little more tricky. There isn't a binding for this function, but if you can use C you can use the _sample info_ of each sample and look at the _instance handle_. You can then use `dds_get_matched_publication_data` from the C API on the reader and instance handle on the receiver side to obtain a `dds_builtintopic_endpoint_t`. That struct contains a `dds_qos_t` which you can inspect with the various `dds_qget_` functions.
