### ISSUE TITLE
Broken C++11 since Mar 18 2022

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-cxx#278]
Broken C++11 compatibility since Mar 18 2022 see here https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commit/b6310e37d325b48d1c5b14484e938b250d878660
Prior to this i was able to use cyclonedds_cxx  with c++11 projects, see here ref #185

So far i investigated two problems:

#### Problem 1: static_assert
(static_assert syntax changed since c++17)
https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/fdbef1f77433cdac9957ab3001f50af6ef42b08e/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp#L256
Possible fix:
```
  #if __cplusplus >= 201703L // c++17 or higher
  static_assert(sizeof(T) == 1 || sizeof(T) == 2 || sizeof(T) == 4 || sizeof(T) == 8);
  #else
  static_assert(sizeof(T) == 1 || sizeof(T) == 2 || sizeof(T) == 4 || sizeof(T) == 8, "");
  #endif
```
#### Problem 2: std::enable_if_t
(Its a c++14 feature)
https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/fdbef1f77433cdac9957ab3001f50af6ef42b08e/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp#L253

### Questions

Hey @eboasson 😊 i wanted to ask you if c++11 compatibility is still "something we intend to be"?
https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/185#issuecomment-989684242

@reicheratwork may you know a workaround to solve Problem 2 for me? It would be awesome for me 😃

**Comment by eboasson** [comment]
@trittsv C++11 compatibility is definitely still a thing. We don't want to lose out on the good things that later versions give us, but as it can be done with modest effort, it is worth it in my opinion. Perhaps "gnu++11" would be a good compromise to avoid having to deal with Visual Studio's idiosyncrasies.

For the `static_assert`, I think I would simply leave the static assert out if not C++17 or later, or perhaps `#define` the problem away. The `std::enable_if_t` problem should be solvable easily enough, if I am correct in my very simple interpretation of https://en.cppreference.com/w/cpp/types/enable_if . What do you think?

If with those small changes it is compatible again with C++11, then let's go for it. And add a `-std=c++11` build to the CI as well!

Side note: there's #271 which I just now realise I completely forgot about once I decided it had to wait until the 0.9.0 release (so sorry @reicheratwork ...) and there is the (still draft) #259. I think neither has any fundamental effect on C++11 compatibility, but it be worth checking.
