### ISSUE TITLE
idl generator confusing string with String

### ISSUE THREAD

**Issue by nate800** [eclipse-cyclonedds/cyclonedds-cxx#286]
This definition works with the type generator.  
```
struct String_t {
    string data;
};
```
However, this idl definition will not work.  
```
struct String {
    string data;
};
```

**Comment by eboasson** [comment]
IDL is case insensitive, so `String` collides with the reserved word `string` (see section 7 of the OMG IDL spec).

**Comment by nate800** [comment]
you are correct.  Section 7.2.3.1 provides collision rules - https://www.omg.org/spec/IDL/4.2/PDF
