### ISSUE TITLE
<Package>Config.cmake files not being installed

### ISSUE THREAD

**Issue by ithier** [eclipse-cyclonedds/cyclonedds-cxx#3]
The cmake files required for find_package are not being generated/installed.

**To reproduce:**
    $ cmake -Bbuild . -DCMAKE_PREFIX_PATH=$PREFIX_PATH -DCMAKE_INSTALL_PREFIX=$INSTALL_DIR
    $ cd ./build
    $ cmake --build . --target install -j8

**Expected:**
CycloneDDS-CXXConfig.cmake files are installed in $INSTALL_DIR/lib/cmake/CycloneDDS-CXX

**Actual:**
Files do not exist in the install directory.

**Comment by k0ekk0ek** [comment]
Hi @ithier. The readme is still what it was in the original repository, so not all instructions are be up-to-date yet. Since this is a quick fix, I'll have a look. Nice to see people are interested :slightly_smiling_face:. Thanks for reporting.
