### ISSUE TITLE
Release build on windows failing in creation of the domain participant

### ISSUE THREAD

**Issue by mw-senthil** [eclipse-cyclonedds/cyclonedds-cxx#305]
Originally posted in [Cyclonedds](https://github.com/eclipse-cyclonedds/cyclonedds/issues/1375). After some debugging found the following
So posting here as well

**dds::domain::DomainParticipant myParticipant(0); //domain id zero**

crashes in Visual Studio 2019 with RelWithDebInfo configuration

When stepped into code in T:\CycloneDDS\cyclonedds-cxx\src\ddscxx\src\org\eclipse\cyclonedds\domain\DomainParticipantDelegate.cpp
DomainParticipantDelegate constructor is getting config with garbage. Looks like there is some template issue

In the debug build config = "" and config.empty() is true

in release build config is random string (looks like memory corruption) and goes into crashing quickly in ntdll.
` ntdll.dll!RtlReportCriticalFailure�() Unknown
ntdll.dll!RtlpHeapHandleError�() Unknown
ntdll.dll!RtlpHpHeapHandleError�() Unknown
ntdll.dll!RtlpLogHeapFailure�() Unknown
ntdll.dll!RtlpAllocateHeap�() Unknown
ntdll.dll!RtlpAllocateHeapInternal�() Unknown
ucrtbased.dll!heap_alloc_dbg_internal(const unsigned __int64 size, const int block_use, const char * const file_name, const int line_number) Line 359 C++
ucrtbased.dll!heap_alloc_dbg(const unsigned __int64 size, const int block_use, const char * const file_name, const int line_number) Line 450 C++
ucrtbased.dll!_malloc_dbg(unsigned __int64 size, int block_use, const char * file_name, int line_number) Line 496 C++
ucrtbased.dll!malloc(unsigned __int64 size) Line 27 C++
ddsc.dll!ddsrt_malloc_s(unsigned __int64 size) Line 21 C
ddsc.dll!ddsrt_malloc(unsigned __int64 size) Line 26 C
`

Even forcing config to be "" causes errors while creating some other entity qos, etc.

Constructor for reference:
`org::eclipse::cyclonedds::domain::DomainParticipantDelegate::DomainParticipantDelegate ( uint32_t id, const dds::domain::qos::DomainParticipantQos& qos, dds::domain::DomainParticipantListener *listener, const dds::core::status::StatusMask& event_mask, const std::string& config ) : domain_id_ (id), qos_(qos) { org::eclipse::cyclonedds::domain::DomainWrap::map_ref_iter it;`

**Comment by eboasson** [comment]
I see I should've responded here ... well, no matter. I responded on https://github.com/eclipse-cyclonedds/cyclonedds/issues/1375

**Comment by mw-senthil** [comment]
Need to use --config for build as well. See the comment in https://github.com/eclipse-cyclonedds/cyclonedds/issues/1375
