### ISSUE TITLE
CMake Error: INSTALL(EXPORT) given unknown export "CycloneDDS-CXX"

### ISSUE THREAD

**Issue by fengtuo58** [eclipse-cyclonedds/cyclonedds-cxx#314]
hi, i intergrate this repo to sub cmake, the dir structure is follow:
├── CMakeLists.txt
├── cyclonedds-cxx
│   ├── CMakeLists.txt
│   └── ...
├── cyclonedds
│   ├── CMakeLists.txt
│   ├── ...

**Comment by thijsmie** [comment]
Without having any details on what your top level CMakeLists.txt looks like it I have no chance to reproduce your issue. The use case of a depending build in one CMake build is actually interesting, would be nice to get that working.
