### ISSUE TITLE
Couldn't build cyclonedds-cxx with example

### ISSUE THREAD

**Issue by KhanalBijay** [eclipse-cyclonedds/cyclonedds-cxx#318]
The build was perfect without including example, but when I tried to build with example, I got this type of error
```
[ 88%] Generating HelloWorldData.hpp, HelloWorldData.cpp
/usr/local/bin/idlc: symbol lookup error: /usr/local/bin/idlc: undefined symbol: DDS_XTypes_TypeObject_desc
make[2]: *** [examples/helloworld/CMakeFiles/helloworlddata_generate.dir/build.make:64: examples/helloworld/HelloWorldData.hpp] Error 127
make[1]: *** [CMakeFiles/Makefile2:308: examples/helloworld/CMakeFiles/helloworlddata_generate.dir/all] Error 2
make: *** [Makefile:152: all] Error 2
```
Has anyone faced this sort of error? I followed [this](https://github.com/eclipse-cyclonedds/cyclonedds-cxx#building-the-eclipse-cyclone-dds-c-binding) instruction on Ubuntu 20.04 device.

**Comment by dpotman** [comment]
Could it be the case that the IDL compiler `/usr/local/bin/idlc` that is used during the build (should be the one from the Cyclone DDS installation path you specified using CMAKE_PREFIX_PATH), uses a `ddsc` shared library that is built without type discovery? Could you check the `ldd` output (`ldd /usr/local/bin/idlc | grep ddsc`)?

**Comment by KhanalBijay** [comment]
I had ros in my pc before installing cyclonedds, so it probably was pointing to ros IDL. I got following output with this(```(ldd /usr/local/bin/idlc | grep ddsc)```:
* ```libddsc.so.0 => /opt/ros/foxy/lib/x86_64-linux-gnu/libddsc.so.0 (0x00007f4e3baef000)```

**Comment by dpotman** [comment]
The Cyclone library that is shipped with ROS does not have type discovery enabled, so it does not export `DDS_XTypes_TypeObject_desc`. If you set `LD_LIBRARY_PATH` to `/usr/local/lib/` when building the C++ binding, the linker will use the correct version of libddsc (which is built with type discovery enabled) and it can resolve the symbols, so then it should build without errors.

**Comment by KhanalBijay** [comment]
Yep, the build process ran with out any error. Thank you @dpotman for your valuable suggestion and guidance.

Closing issue for now.
