### ISSUE TITLE
Qos  RPC   example

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds-cxx#334]
I have a question to ask, do you support rpc, but I didn't find the relevant description, and another question, is there a better demo in c++ to learn to use interface functions and QoS

**Comment by thijsmie** [comment]
Please refer to the [c++ section in the getting started guide](https://cyclonedds.io/docs/cyclonedds/latest/getting_started.html#installing-eclipse-cyclone-dds-cxx) and take a look at the examples in the repo.

On the topic of RPC: we do not (currently) implement the RPC-over-DDS specification for CycloneDDS (https://www.omg.org/spec/DDS-RPC). Now I am not a great fan of this spec anyway, and I am of the opinion that you can use regular datatypes tailored to your purpose and building a regular DDS application you can achieve the same thing without a bunch of headaches that come with that spec.
