### ISSUE TITLE
arm cross compile cyclonedds idl   error  

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds-cxx#335]
cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/toolchain.cmake \
           -DCMAKE_BUILD_TYPE=Release \ 
          -DCMAKE_INSTALL_PREFIX=/ddsinstall/stage  \
          ../..
-- Building with OpenSSL support
CMake Error at cmake/Modules/Generate.cmake:44 (find_program):
  Could not find _idlc_executable using the following names: idlc
Call Stack (most recent call first):
  cmake/Modules/Generate.cmake:32 (idlc_generate_generic)
  examples/helloworld/CMakeLists.txt:24 (idlc_generate)

**Two questions** 
1. Openssl I directly replaced the local compiled link. My understanding is whether there is an openssl that automatically replaces gcc and arm in the program.
2. After cross-compiling, the idl idlc tool cannot be generated. Is there any way?

**Comment by ThijsSassen** [comment]
@wjbbupt you can generate idlc on the host by doing

mkdir host-build
cd host-build
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake  --build . --config Release --target idlc

when you have done that you can add the bin dir to your prefix path of the cross compile so it can use the host idlc compiler.

cmake -DCMAKE_TOOLCHAIN_FILE=/tmp/toolchain.cmake -DCMAKE_BUILD_TYPE=Release -CMAKE_INSTALL_PREFIX=/ddsinstall/stage -DCMAKE_PREFIX_PATH=build-host/bin ../..

**Comment by wjbbupt** [comment]
First of all, thank you very much for your ideas, but I just tried the method you provided here. The compiled binary file is still x86_64.
My purpose is to cross-compile in ubuntu environment to generate examples of arm version, put it on the machine with arm architecture and run the examples. Do you have a complete compilation process or command?
There is something I want to learn, thank you very much, and wish you a happy life!

**Comment by thijsmie** [comment]
Hi @wjbbupt,

First of all, I understand you might be a new user, but that is no reason to open multiple issues and place many reactions under vaguely related issues. Please open a single issue where you describe your problem and have a little patience for us open source maintainers to get back to you. You can also post in our discord server, where we or other users might help you out in a more direct one-to-one.

Next, you do not need `idlc` for arm8 if you are cross-compiling. `idlc` is a *build tool* so is used at compile time to turn IDL into C code which you can then compile. Therefore it is logical that `idlc` is still x86_64, you will only use it on the host machine. I recommend you pass `-DBUILD_IDLC=off` for your second CMake invocation that has the toolchain.
