### ISSUE TITLE
issue in idlcxx generated code for the sequence of non-primitive type in Discriminated Union

### ISSUE THREAD

**Issue by vivekpandey02** [eclipse-cyclonedds/cyclonedds-cxx#343]
Hi Erik & Martijn,
I got some issue into the idlcxx generated code for the sequence of non-primitive type in Discriminated Union.
Basically, I am using RnR.idl, union is below:

union Kind switch(CommandKind) {
        case ADD_RECORD_COMMAND:                /* Record command */
            AddRecordCommand addRecord;
        case REMOVE_RECORD_COMMAND:
            RemoveRecordCommand removeRecord;
        case ADD_REPLAY_COMMAND:                /* Replay command */
            AddReplayCommand addReplay;
        case REMOVE_REPLAY_COMMAND:
            RemoveReplayCommand removeReplay;
        case CONFIG_COMMAND:                    /* Config command */
            **sequence<KeyValue> config;**
        case START_SCENARIO_COMMAND:            /* Scenario-control commands */
        case STOP_SCENARIO_COMMAND:
        case SUSPEND_SCENARIO_COMMAND:
            string name;
        case SETREPLAYSPEED_COMMAND:            /* Storage replay-speed command */
            SetReplaySpeedCommand setreplayspeed;
        case TRUNCATE_COMMAND:                  /* Storage truncate command */
            string storage;
        case GENERIC_COMMAND:                   /* For future extensibility */
            **sequence<KeyValue> extCommands;**
    };

Here is the error with the sequence<KeyValue>:

/mnt/d/Workspace/RnR.hpp: In function ‘bool org::eclipse::cyclonedds::core::cdr::write(T&, const RnR::Kind&, org::eclipse::cyclonedds::core::cdr::entity_properties_t*)’:
/mnt/d/Workspace/RnR.hpp:9918:52: error: ‘prop’ was not declared in this scope; did you mean ‘props’?
 9918 |       if (!write(streamer, instance.config()[i_1], prop))
      |                                                    ^~~~
      |                                                    props
/mnt/d/Workspace/RnR.hpp:9956:57: error: ‘prop’ was not declared in this scope; did you mean ‘props’?
 9956 |       if (!write(streamer, instance.extCommands()[i_1], prop))
      |                                                         ^~~~
      |                                                         props

**Comment by reicheratwork** [comment]
Looks like the streaming functions are thinking that they are in a struct with regards to the member they are streaming, so they think that they have the properties for member `prop` to give to the streamer.

I will work on a fix and reference this issue when I make a PR, @vivekpandey02 .

**Comment by vivekpandey02** [comment]
Hi Martijn,
I have tested with your fixed. It is working now. I appreciate your prompt action. 

Thank you so much.

With best regards,
Vivek
