### ISSUE TITLE
c++  batch 

### ISSUE THREAD

**Issue by wjbbupt** [eclipse-cyclonedds/cyclonedds-cxx#352]
Tested c++ throughput and found that c++ did not integrate batch well, and then I added batch to the header file used, and the test found that it did not take effect, but the batch function print of c showed that it was transferred.
So I would like to ask what things need to be paid attention to when C++ integrates batch?

**Comment by eboasson** [comment]
This is a bit cryptic, but I suspect I know what you are trying to describe.

I have noticed a silly bug in `dds_set_batch` in that you have to call it *before* creating the writers, even though it was intended to work at any time (I could fix that, if needed). Is it possible that this is what you ran into?

Note that it ought to be per-writer anyway, but it is also an unofficial, unstable API that simply hangs in there until it gets replaced by a better solution.

**Comment by wjbbupt** [comment]
My side is needed, help send it, how to modify it, thanks and thanks

**Comment by wjbbupt** [comment]
@eboasson  This is what I need, so I'm busy repairing it. The batch for the next batch of adjustments, the result is no live effect because I've seen it before, and there are many batches for the first round of adjustments;
1, if this is a bug that can be fixed, please fix the problem with c++ adjustment.
2. Some c++ implementation，Integrated batch function，It is possible to solve it，I hope this can be fixed，Thank you
