### ISSUE TITLE
Batched writing is not supported

### ISSUE THREAD

**Issue by reicheratwork** [eclipse-cyclonedds/cyclonedds-cxx#366]
Whereas CycloneDDS-C supports batched writing through the function `dds_write_set_batch`, but CycloneDDS-CXX does not have this functionality.
Probably due to it not being part of the spec.

To implement this, I propose we add a function "to the side of the spec" which does allow us to set this property.
This only needs to propagate this call to the C layer and not retain any state inside the C++ layer.

**Comment by reicheratwork** [comment]
We will need a function that will set the batch mode of a writer (the C++ equivalent to `dds_write_set_batch`)
and a function to flush a writer's batched writes (the C++ equivalent to `dds_write_flush`)

**Comment by matthew-ivester** [comment]
I'm pretty sure `dds_write_set_batch` toggles the batching on/off for the whole process, not an individual DataWriter.  There doesn't seem to be a way to change the batching settings for an individual DataWriter after its creation in the C API.

A flush call is actually implemented in the `AnyDataWriterDelegate` class, but it's not exposed in the public `DataWriter<T>` API.  So if you create a writer on a domain that has batching configured, you can flush it by doing:

```
dataWriter.delegate()->write_flush();
```

This also seems like a thing that could be added to the `DataWriter` API, some other DDS implementations include extension methods like this.

**Comment by eboasson** [comment]
> I'm pretty sure dds_write_set_batch toggles the batching on/off for the whole process, not an individual DataWriter

I know. It is trivial to change and it suffered from the "perfect is the enemy of good" problem. There are vastly better solutions than anything involving this "batch" flag, but if there is always something that interferes with actually doing any of those, then the end result is not so great.

So perhaps I should overcome my distaste for improving the `set_batch` interface and make it per-writer ... I kind of think that setting "latency budget" to ∞ would be a good choice, but: (1) you also want to use the latency budget setting to choose between synchronous/asynchronous publishing in my view; and (2) latency budget is one of those annoying RxO QoS settings and setting the latency budget to ∞ on the writer would mean all readers would have to use ∞ as well, but unfortunately ∞ is not the default for readers ...

A separate QoS setting would therefore probably be the best way to do it. Adding it to the C code is quite trivial, adding it to the C++ code probably requires a few more lines but those follow the established pattern. Extending the DataWriter with a `write_flush` call is then easily done as well.

It probably makes the most sense to start with a PR on the `cyclonedds` repository for adding the QoS.

**Comment by eboasson** [comment]
Yes, #406 added it. For example: https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/c64812f3e33f31281435c823c5f615dcdad08bcd/examples/throughput/publisher.cpp#L199-L200 and https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/c64812f3e33f31281435c823c5f615dcdad08bcd/examples/throughput/publisher.cpp#L153

Thanks for asking, my apologies for forgetting to reference this issue. As the feature is supported now, I'll close the issue 🙂
