### ISSUE TITLE
Key definition does not work properly

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-cxx#375]
In the key-syntax (`@key` before the attribute) the attribute is not 'really' declared key
if a struct with name `Key` is defined before (in same file, in same module).

In the following example ActorInfo does not get a key (`TopicTraits<::ddActorInfo::ActorInfo>::isKeyless() == true`)
until the struct is renamed from `Key` to for example `Key1`.
Also a warning is output, if the error occurs on call: `idlc -l cxx .../xyz.idl`
`xyz.idl:X:Y: Unrecognized annotation: @key`

```idl
module ddActorInfo
{
  struct Process
  {
      string           ipAddress;
  };
  struct Key
  {
      string           serviceName;
  };
  struct ActorInfo
  {
      @key
      string           actorId;
      int32            sequenceId;
  };
};
```
It works with other dds vendors.
@eboasson doe the idl syntax look right to you?

Is there a possibility to let idlc return an error-code (and not 0) after emitting such an error-message? (-Werror?) this would help very much 😃

**Comment by eboasson** [comment]
That IDL looks fine to me, which makes it an "interesting" bug in IDLC. Name-space confusion, I guess, although I really should double-check the spec before declaring it bug: maybe they nowadays do occupy the same name space ... But even if that is the case, I am of the opinion that this should be allowed.

Also +1 for `-Werror`!
