### ISSUE TITLE
Listener does not work reliable

### ISSUE THREAD

**Issue by trittsv** [eclipse-cyclonedds/cyclonedds-cxx#378]
Hey,  i dont receive always callbacks from a `DataReaderListener` (except `on_data_available`) depending on how i register the listener.
"Not always" means that from around 10 tries 1 try without callbacks (except `on_data_available`).

Setup: Exchange hello between publisher and subscriber executable with CycloneDDS-CXX 0.10.2.

## 1. Case where Listener always works
```cpp
dds::sub::DataReader<HelloWorldData::Msg> reader(subscriber, topic,
    subscriber.default_datareader_qos(),
    new ExampleListener(),
    dds::core::status::StatusMask::all()
);
```
```bash
./subscriber 
=== [Subscriber] Create reader.
=== [Subscriber] Wait for message.
on_subscription_matched, current_count: 1
on_liveliness_changed
on_data_available
=== [Subscriber] Message received:
    userID  : 1
    Message : "Hello World"
Sleeping ...
=== [Subscriber] Done.
```

## 2. Case where listener does not work reliable except "on data"
```cpp
dds::sub::DataReader<HelloWorldData::Msg> reader(subscriber, topic);
auto *listener = new ExampleListener();
reader.listener(listener, dds::core::status::StatusMask::all());
```
```bash
./subscriber
=== [Subscriber] Create reader.
=== [Subscriber] Wait for message.
on_data_available
=== [Subscriber] Message received:
    userID  : 1
    Message : "Hello World"
=== [Subscriber] Done.
```
In the bad case: even when i first close the publisher executable and let the subscriber run a while no liveless changes or other callbacks are received (except on_data).

It seems that sometimes something went wrong when setting the listener via the setter method.
I did not use any configuration except enabling tracing.

Here is the full code with cyclonedds trace files in good and bad case:
[listener-not-reliable.zip](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/files/10918029/listener-not-reliable.zip)
See `subscriber.cpp`.

@eboasson should my example work above? Or did i understand something conceptually wrong?

**Comment by trittsv** [comment]
Thanks for your answers. I just was able to reproduce it also with the "good case".

In our application the first `on_publication_matched` never gets called when the reader is started first and few seconds later the writer. 

But when i start the writer first then always the first `on_publication_matched` is called like it should.

@eboasson are there any rules that the writer has to be first opened in order that everything works correctly?

**Comment by eboasson** [comment]
> In our application the first on_publication_matched never gets called when the reader is started first and few seconds later the writer.

Then I definitely need to have a second look. That's not how it is supposed to be!

The trace you attached might help with that if it happens to be this case where the reader is started first; but I can also try to reproduce it with my (infamous) `oneliner` test-tool.

**Comment by tez1szh** [comment]
I've fixed this issue a few days ago.
The patch is available but on another PC which I can only access tomorrow.

I'll create a pull request soon.

**Comment by tez1szh** [comment]
I've fixed this issue a few days ago.
The patch is available but on another PC which I can only access tomorrow.

I'll create a pull request soon.

**Comment by eboasson** [comment]
@trittsv I just merged @tez1szh's PR, so it should be fixed now (on master)

**Comment by trittsv** [comment]
@tez1szh awesome thank you very much, this fixed our problem too.

@eboasson this ticket can be closed 🚀
