### ISSUE TITLE
[question] ContentFilteredTopic Maturity

### ISSUE THREAD

**Issue by swhinton** [eclipse-cyclonedds/cyclonedds-cxx#396]
Cyclone DDS C version is 0.10.3
Cyclone DDS CXX version is 0.10.3

Hello, and thank you for all of the awesome work!

I'm still a DDS newbie, so please forgive me if this is a dumb question or I've missed something, I still have much to learn and I've been prototyping in conjunction with reading documentation to do so. I have a very simple Topic, like this: 

```
enum FooBarEnum {
  FOO,
  BAR
};

union FooBarUnion switch (FooBarEnum) {
  case FOO:
    float fooValue;
  default:
    long barValue;
};

struct FooBarStruct {
  @key octet sensorId;
  FooBarEnum fooBarEnum;
  FooBarUnion fooBarUnion;
  ...
};
```

I create a data reader for the filtered topic like so:
```
    std::vector<std::string> params;
    params.push_back("1");
    dds::topic::Filter filter{"sensorId=%0", params};

    dds_participant = dds::domain::DomainParticipant(default_id());
    topic = dds::topic::Topic<FooBarStruct>(dds_participant, "FooBar");

    filtered_topic = dds::topic::ContentFilteredTopic<FooBarStruct>(topic, "FilteredFooBar", filter);

    subscriber = dds::sub::Subscriber(dds_participant);
    reader = dds::sub::DataReader<FooBarStruct>(subscriber, filtered_topic);

```

But Cyclone DDS throws an exception:
```
DDS Exception: Error Bad Parameter - Could not create DataReader.
===============================================================================
Context     : void dds::sub::detail::DataReader<T>::common_constructor
Node        : UnknownNode
```

I haven't yet dug into the source code beyond looking for examples in the tests (which are TODO for ContentFilteredTopic, darn), so I'm not exactly sure if I've done something wrong or this is a bug.

**Comment by eboasson** [comment]
Hi @swhinton, you haven't not done anything wrong and you're not the only one running into this either.

The problem used to be that expressions like `"sensorId=%0"` require knowledge of the type but we didn't have the metadata available. Today, we *do* have the metadata and we know how to put that to use for this, but we still need to find the time.

Cyclone does provide a workaround where you provide a function that evaluates the filter expression instead. This https://github.com/eclipse-cyclonedds/cyclonedds-cxx/issues/253#issuecomment-1087452070 should help to get you started (assuming this workaround of passing a function is acceptable to you).

**Comment by swhinton** [comment]
Wow, sorry I missed that! Yes, the filter expression is acceptable, thank you for that guidance!
