### ISSUE TITLE
key definition in idl file does not work for inheritance structure

### ISSUE THREAD

**Issue by SeanYu81** [eclipse-cyclonedds/cyclonedds-cxx#397]
Hello Guys,

    Thanks for your support in advance.
    When I test IDL generation for inheritance structure with key definition, I find one problem. The following gives more information.
    1. CycloneDDS builds are based on latest master branch including cyclonedds-c and cyclonedds-cxx. (date: 04/21/2023)
    2. Test example comes from official helloworld example in cyclonedds-cxx project.
    3. I only change HelloWorldData.idl file to add inheritance structure as below. SubMsg is inherited from Msg, and Msg structure has key definition.
        ---------------------------
        module HelloWorldData
        {
          struct Msg
          {
            @key long userID;
            string message;
          };
        
          struct SubMsg: Msg
          {
            string value;
          };
        };
        ---------------------------
    5. Using official build procedure to compile helloworld example, and checking IDL generation file HelloWorldData.hpp. In HelloWorldData.hpp, there is isKeyless() function to be generated for SubMsg. 
        ---------------------------
       template <> constexpr bool TopicTraits<::HelloWorldData::SubMsg>::isKeyless()
        {
          return true;
        }
        ---------------------------

    Per my understanding, key is defined in Msg and isKeyless() function is not generated for ::HelloWorldData::Msg. I think it is correct. However, for SubMsg I think it should also have key definition because of inheritance from Msg, and isKeyless() function should also not be generated for ::HelloWorldData::SubMsg. Is it correct? 
    
    If possible, would you like to give any comments for this problem? Thanks.

Regards,
Sean Yu

**Comment by eboasson** [comment]
I agree.

Trying it out it seems one actually does have to generate the `isKeyless` trait for inherited types (when there really is no key).

**Comment by SeanYu81** [comment]
Thanks, @eboasson
