### ISSUE TITLE
unmatched serialization and deserialization function invocations when using SHM

### ISSUE THREAD

**Issue by SeanYu81** [eclipse-cyclonedds/cyclonedds-cxx#407]
Hello Guys,
    
    Thanks for your support in advance!
    Recently, I am testing cyclonedds SHM communication, so I refer to official document to build/setup SHM environment (https://cyclonedds.io/docs/cyclonedds/latest/shared_memory/shared_memory.html).
    When I run my test case, SHM does not work as I expected. The test case always generates core dump due to invalid memory access. Related error message comes from cyclonedds-cxx function.
    -------------------------------------------
    include/ddscxx/org/eclipse/cyclonedds/topic/datatopic.hpp:69: bool to_key(const T&, ddsi_keyhash_t&) [with T = AgvStartStop; ddsi_keyhash_t = ddsi_keyhash]: Assertion `false' failed.
    Aborted (core dumped)
    -------------------------------------------
    
    In order to debug this problem and try to find the root cause, I use gdb debugger to track test case execution procedure step by step. Finally, I find the problem maybe come from unmatched serialization and deserialization function invocations. The following lists a brief callflow.
    -------------------------------------------
    dds_write_impl (dds_writer *wr, const void * data, dds_time_t tstamp, dds_write_action action) in dds_write.c
    --> dds_write_impl_iox (wr, ddsi_wr, writekey, data, tstamp, action)
          --> get_iox_chunk (wr, data, &iox_chunk)
                --> create_and_fill_chunk (wr, data, iox_chunk)
                      --> shm_create_chunk (wr->m_iox_pub, required_size)
                      --> fill_iox_chunk (wr, data, *iox_chunk, required_size)
                            --> ddsi_sertype_serialize_into(wr->m_wr->type, sample, iox_chunk, size)
                                   --> tp->ops->serialize_into(tp, sample, dst_buffer, dst_size)
                                          (**Note: in serialize_into function, buffer is filled with 3 calls(write_header, write, finish_header). So the buffer is not equal to sample!!!** )
          --> ddsi_serdata_from_loaned_sample (ddsi_wr->type, writekey ? SDK_KEY : SDK_DATA, iox_chunk)
                --> type->serdata_ops->from_iox_buffer (type, kind, NULL, (void *) sample)
                      --> serdata_from_iox_buffer(const struct ddsi_sertype * typecmn, enum ddsi_serdata_kind kind, void * sub, void * iox_buffer) in datatopic.hpp
                            (**Note: in serdata_from_iox_buffer function, the buffer(d->iox_chunk) is directly casted to sample(msg). Actually, in above logic, the buffer has prefix header + serialized data, and it should not be directly casted**).               
    -------------------------------------------

    I make some changes in serdata_from_iox_buffer function as follows and rerun the test case. Now everything is OK. So please help to review whether these changes are reasonable.
    in serdata_from_iox_buffer function from datatopic.hpp
    -------------------------------------------
    Change
        **const auto& msg = *static_cast<const T*>(d->iox_chunk);**
    To 
        **T msg;
        iceoryx_header_t *iox_header = iceoryx_header_from_chunk(d->iox_chunk);
        if (!deserialize_sample_from_buffer(d->iox_chunk, iox_header->data_size, msg, kind)) {
            return nullptr;
        }** 
    -------------------------------------------
   
    I download the latest cyclonedds-c/cyclonedds-cxx/iceoryx codes to build headers and libraries for testing.
    
    Appreciate your help.

Regards,
Sean Yu

**Comment by reicheratwork** [comment]
@SeanYu81 : I suggest we close this issue, as the associated PR is closed.

**Comment by eboasson** [comment]
@SeanYu81 I am closing this because I agree with @reicheratwork. If that was a mistake, please just reopen it.
