### ISSUE TITLE
Question about how to keep generated files identical to idl files in CMake?

### ISSUE THREAD

**Issue by keepgoingxxx** [eclipse-cyclonedds/cyclonedds-cxx#417]
How to keep generated files identical to idl files in CMake?
I want the files generated through idl to be the same as the idl folder structure.

which option I have to use to keep the folder structure?
Could you please give me one example for CMake?

```cmake
# CMakeLists.txt
file(GLOB_RECURSE idl_files RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} idl/**/*.idl)

idlcxx_generate(TARGET my_idl
    FILES ${idl_files}
    INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/idl
    FEATURES case-sensitive
    DEFAULT_EXTENSIBILITY appendable
    WARNINGS no-implicit-extensibility
    ) 
``` 

```shell
idl/
├── fusion
│   └── fusion.idl
└── radar
    └── radar.idl
``` 

as is
```shell
.
├── fusion.cpp
├── fusion.hpp
├── radar.cpp
└── radar.hpp
``` 

to be
```shell
├── fusion
│   ├── fusion.cpp
│   └── fusion.hpp
└── radar
    ├── radar.cpp
    └── radar.hpp
``` 
Thank you in advance.

**Comment by reicheratwork** [comment]
Hello @keepgoingxxx , it seems like there is a feature that **is** present in the CycloneDDS-C generation script `idlc_generate` missing in its CycloneDDS-CXX equivalent `idlcxx_generate` which would suit your requirements, I think.

I am talking about the `BASE_DIR` function parameter, which is supplied to `idlc` as the `-b` argument.
This will make idlc attempt to replicate the directory structure of the input file starting at the indicated base directory.

So if ask it to parse the following files:
- `/a/b/c/1.idl`
- `/a/b/c/2.idl`
- `/a/d/e/3.idl`
- `/a/d/e/4.idl`

with as base directory `/a/`
It would create the following files in the selected output directory:
- `b/c/1.h`
- `b/c/1.c`
- `b/c/2.h`
- `b/c/2.c`
- `d/e/3.h`
- `d/e/3.c`
- `d/e/4.h`
- `d/e/4.c`

Now, at the moment, `idlcxx_generate` does not have a `BASE_DIR`, so I will look into creating this functionality in CycloneDDS-CXX.

**Comment by keepgoingxxx** [comment]
Hello @reicheratwork, Thank you for your kindly reply.

Oh.. Now only C generator has the feature.
To your knowledge, how did you deal with this when many idl files are in multiple folders?
Is there any way to handle this? (except for the method of simply creating folder and copying it)

Thank you in advance.

**Comment by reicheratwork** [comment]
> Hello @reicheratwork, Thank you for your kindly reply.
> 
> Oh.. Now only C generator has the feature. To your knowledge, how did you deal with this when many idl files are in multiple folders? Is there any way to handle this? (except for the method of simply creating folder and copying it)
> 
> Thank you in advance.

Looking back, having to deal with having to restructure the generated files never really occurred to me, so I can't really say how to deal with it in that way.

In any case, there is a fix for this in PR #418 .

**Comment by eboasson** [comment]
@keepgoingxxx I merged #418, so this should have been addressed now.

**Comment by reicheratwork** [comment]
@keepgoingxxx:
The way output directories work in idlcxx work now is as follows:

Assuming you have the following directory structure in the same directory your cmake file is in:
```
data/try_1/try_2_1/f_2_1_1.idl
data/try_1/try_2_1/f_2_1_2.idl
data/try_1/try_2_2/f_2_2_1.idl
data/try_1/try_2_2/f_2_2_2.idl
```

Then by using the following call to `idlcxx_generate`
```
idlcxx_generate(TARGET ddscxx_test_types2
BASE_DIR data/try_1/
FILES
data/try_1/try_2_1/f_2_1_1.idl
data/try_1/try_2_1/f_2_1_2.idl
data/try_1/try_2_2/f_2_2_1.idl
data/try_1/try_2_2/f_2_2_2.idl)
```
, you indicate that idlc should use `data/try_1/` as the base directory for reconstructing the directory structure of the output files, and it cuts that part of the path off, and leaves the rest of the directory structure intact for the output files.

Resulting in the following filestructure being generated in the output directory:
```
try_2_1/f_2_1_1.hpp
try_2_1/f_2_1_2.hpp
try_2_2/f_2_2_1.hpp
try_2_2/f_2_2_2.hpp
try_2_1/f_2_1_1.cpp
try_2_1/f_2_1_2.cpp
try_2_2/f_2_2_1.cpp
try_2_2/f_2_2_2.cpp
```

I think this very closely approaches what you want, and then the rest you can adjust with globbing etc.

**Comment by keepgoingxxx** [comment]
@reicheratwork, Thank you for quick reply.

When I tested it, it was working well you mentioned folder structure.
however, if the idl folder structure like below it occured error.

**Error message**
```
CMake Error at /usr/local/lib/cmake/CycloneDDS/idlc/Generate.cmake:171 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.
``` 

**Folder structure**
```shell

./depth1/depth2/depth.idl
./fusion/fusion.idl
./HelloWorldData.idl
./radar/radar.idl
./sensor/sensor.idl


.
├── depth1
│   └── depth2
│       └── depth.idl
├── fusion
│   └── fusion.idl
├── HelloWorldData.idl
├── radar
│   └── radar.idl
└── sensor
    └── sensor.idl

``` 

CMakeLists.txt
```cmake
file(GLOB_RECURSE fusion_idl RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} idl/fusion/*.idl)
file(GLOB_RECURSE radar_idl RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} idl/radar/*.idl)
file(GLOB_RECURSE sensor_idl RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} idl/sensor/*.idl)
file(GLOB_RECURSE depth_idl RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} idl/depth1/depth2/*.idl)
file(GLOB_RECURSE hello_idl RELATIVE ${CMAKE_CURRENT_SOURCE_DIR} HelloWorldData.idl)

idlcxx_generate(TARGET testdata
    FILES ${fusion_idl} ${radar_idl} ${sensor_idl} ${depth_idl} ${hello_idl}
    INCLUDES ${CMAKE_CURRENT_SOURCE_DIR}/idl
    FEATURES case-sensitive
    DEFAULT_EXTENSIBILITY appendable
    BASE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/idl
    WARNINGS no-implicit-extensibility
    )

``` 

Could you please check this case?

**Comment by strudyalgorithm** [comment]
@reicheratwork Thank you for your quick support!

I've been on a pretty long vacation. 
So I saw your answer late. sorry. 

Your patch seems to work perfectly for the issue.

Thank you!

**Comment by reicheratwork** [comment]
@strudyalgorithm glad I could help!

I think we can close this issue then?

**Comment by keepgoingxxx** [comment]
@reicheratwork, Thank you for your quick support!

I've been on a pretty long vacation.
So I saw your answer late. sorry.

Your patch seems to work perfectly for the issue.

We can close this ticket thank you!
