### ISSUE TITLE
Fix for issue #293 not in latest release

### ISSUE THREAD

**Issue by TimMooreAu** [eclipse-cyclonedds/cyclonedds-cxx#451]
Hello,

I'm wondering if the Fix for issue #293 was deliberately left out of release 0.10.4? I'd like to use a specifically numbered release if possible, but perhaps I'm better off just using the latest master?

Thanks

**Comment by eboasson** [comment]
Sorry for the very long delay ...

It was not specifically left out of 0.10.4, I overlooked it.

If you're ok with using latest master, then that's what I would prefer, but this is a bug that in my view is bad enough to do a 0.10.5 if there's a need for it.

**Comment by TimMooreAu** [comment]
No problem, latest master is fine thanks.
