### ISSUE TITLE
question re C++17 for Galactic May 2021

### ISSUE THREAD

**Issue by joespeed** [eclipse-cyclonedds/cyclonedds-cxx#47]
@ThijsSassen this week @clalancette said Open Robotics is thinking about changing to C++17 as minimum for ROS2 Galactic in May (PR to REP-2000 upcoming) and asks to comment if there are any objections.

**Comment by kydos** [comment]
@joespeed that should not pose any issue, actually I am pretty sure that our C++ API already works with C++17.

**Comment by k0ekk0ek** [comment]
Closing this issue. For completeness: we've chosen to require C++17 as a minimum.
