### ISSUE TITLE
Compilation Error in linux

### ISSUE THREAD

**Issue by smsanghavi95** [eclipse-cyclonedds/cyclonedds-cxx#477]
I have compiled The cyclonedds-master and able to run the example but following one is not working.
cmake -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_PREFIX_PATH="../../cyclonedds-master/install/" -DBUILD_EXAMPLES=ON ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:227 (find_package):
  By not providing "FindCycloneDDS.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CycloneDDS", but CMake did not find one.

  Could not find a package configuration file provided by "CycloneDDS" with
  any of the following names:

    CycloneDDSConfig.cmake
    cyclonedds-config.cmake

  Add the installation prefix of "CycloneDDS" to CMAKE_PREFIX_PATH or set
  "CycloneDDS_DIR" to a directory containing one of the above files.  If
  "CycloneDDS" provides a separate development package or SDK, be sure it has
  been installed.

-- Configuring incomplete, errors occurred!

Please help with this.
Thanks in advance.

**Comment by smsanghavi95** [comment]
above issue if fixed but now facing issue as following.
        *__result = *__first;
                  ^
[ 31%] Building CXX object src/ddscxx/CMakeFiles/ddscxx.dir/src/org/eclipse/cyclonedds/core/cdr/fragchain.cpp.o
[ 32%] Building CXX object src/ddscxx/CMakeFiles/ddscxx.dir/src/org/eclipse/cyclonedds/core/cdr/cdr_stream.cpp.o
[ 33%] Building CXX object src/ddscxx/CMakeFiles/ddscxx.dir/src/org/eclipse/cyclonedds/core/cdr/basic_cdr_ser.cpp.o
[ 34%] Building CXX object src/ddscxx/CMakeFiles/ddscxx.dir/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp.o
In file included from /project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp:11:0:
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:105:39: error: ‘std::enable_if_t’ has not been declared
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(!std::is_arithmetic<T>::value && !std::is_enum<T>::value) || (sizeof(T) != 1 && sizeof(T) != 2 && sizeof(T) != 4 && sizeof(T) != 8), bool> = true >
                                       ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:105:50: error: expected ‘>’ before ‘<’ token
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(!std::is_arithmetic<T>::value && !std::is_enum<T>::value) || (sizeof(T) != 1 && sizeof(T) != 2 && sizeof(T) != 4 && sizeof(T) != 8), bool> = true >
                                                  ^
In file included from /project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp:11:0:
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:117:39: error: ‘std::enable_if_t’ has not been declared
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 1, bool> = true >
                                       ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:117:50: error: expected ‘>’ before ‘<’ token
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 1, bool> = true >
                                                  ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:118:21: error: redefinition of ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_8_bits; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:106:21: error: ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’ previously declared here
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_unset; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:129:39: error: ‘std::enable_if_t’ has not been declared
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 2, bool> = true >
                                       ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:129:50: error: expected ‘>’ before ‘<’ token
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 2, bool> = true >
                                                  ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:130:21: error: redefinition of ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_16_bits; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:106:21: error: ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’ previously declared here
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_unset; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:141:39: error: ‘std::enable_if_t’ has not been declared
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 4, bool> = true >
                                       ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:141:50: error: expected ‘>’ before ‘<’ token
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 4, bool> = true >
                                                  ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:142:21: error: redefinition of ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_32_bits; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:106:21: error: ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’ previously declared here
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_unset; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:154:39: error: ‘std::enable_if_t’ has not been declared
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 8, bool> = true >
                                       ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:154:50: error: expected ‘>’ before ‘<’ token
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(std::is_arithmetic<T>::value || std::is_enum<T>::value) && sizeof(T) == 8, bool> = true >
                                                  ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:155:21: error: redefinition of ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_64_bits; }
                     ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:106:21: error: ‘template<class T, int <anonymous> > constexpr org::eclipse::cyclonedds::core::cdr::bit_bound org::eclipse::cyclonedds::core::cdr::get_bit_bound()’ previously declared here
 constexpr bit_bound get_bit_bound() { return bit_bound::bb_unset; }
                     ^
gmake[2]: *** [src/ddscxx/CMakeFiles/ddscxx.dir/src/org/eclipse/cyclonedds/core/cdr/entity_properties.cpp.o] Error 1
gmake[1]: *** [src/ddscxx/CMakeFiles/ddscxx.dir/all] Error 2

**Comment by ThijsSassen** [comment]
hi @smsanghavi95 , cyclone uses c++17 standard by default which is not fully compatible with your gcc version of 4.8.5. Try 
-DENABLE_LEGACY=YES to enable legacy c++11 mode, this adds boost as dependency so you need to include that.

**Comment by smsanghavi95** [comment]
Hi Thanks for response.
this steps i am following.
1.cmake -DCMAKE_INSTALL_PREFIX=../install/ -DCMAKE_PREFIX_PATH="~/Savan/March24/cyclonedds-master/install/" -DBUILD_EXAMPLES=ON -DENABLE_LEGACY=YES  ..
2.cmake --build .
I installed boost 1.53 but getting  following error in cmake --build
here is image
![boostError](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/assets/61928738/d85812a2-918d-4338-bade-3d83e5d9ddf1)

log 
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:105:39: error: ‘boost::enable_if_t’ has not been declared
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(!std::is_arithmetic<T>::value && !std::is_enum<T>::value) || (sizeof(T) != 1 && sizeof(T) != 2 && sizeof(T) != 4 && sizeof(T) != 8), bool> = true >
                                       ^
/project/T0285448/savan/March24/cyclonedds-cxx-master/src/ddscxx/include/org/eclipse/cyclonedds/core/cdr/entity_properties.hpp:105:50: error: expected ‘>’ before ‘<’ token
 template<typename T, DDSCXX_STD_IMPL::enable_if_t<(!std::is_arithmetic<T>::value && !std::is_enum<T>::value) || (sizeof(T) != 1 && sizeof(T) != 2 && sizeof(T) != 4 && sizeof(T) != 8), bool> = true >
                                                  ^

**Comment by ThijsSassen** [comment]
your boost version is too old. you need a boost version that supports at least C++14 as enable_if_t needs it.

**Comment by smsanghavi95** [comment]
Thanks above input worked for me.
Closing this issue.
