### ISSUE TITLE
What is the relationship between cycloneDDS and cycloneDDS-cxx ?

### ISSUE THREAD

**Issue by Jingzhao123** [eclipse-cyclonedds/cyclonedds-cxx#56]
As a freshman in dds, Is there anyone who could help me to clarify the relationship between cycloneDDS and cycloneDDS-cxx ?
Is this project only the dds implementation by C++, no relationship with cycloneDDS?
Thanks very much!

**Comment by eboasson** [comment]
Hi @Jingzhao123, `cyclonedds-cxx` is a C++ language binding for `cyclonedds`, it implements the C++ DDS API (as specified by the OMG) by mapping all the operations to the C API of `cyclonedds`. So you can use `cyclonedds` stand-alone (using the C API), or you can use both (and write modern C++).

**Comment by Jingzhao123** [comment]
Thanks for your help.
