### ISSUE TITLE
idl-cxx: Segmentation fault while reading samples from datareader

### ISSUE THREAD

**Issue by dkroenke** [eclipse-cyclonedds/cyclonedds-cxx#64]
## Required information

**Operating system:**
E.g. Ubuntu 20.04 LTS

**Compiler version:**
E.g. GCC 9.3.0

**Observed result or behaviour:**
On iceoryx we want to update the CycloneDDS and CycloneDDS-CXX from the idl-pp generator to the new idlcxx generator on the `idlcxx` branch. 
The work for this is done here: https://github.com/ApexAI/iceoryx/tree/iox-%23736-update-cyclonedds-to-idlcxx
Generation of the messages is successful and the header files are available.

We have in iceoryx a gateway written that split into two applications:
1. `iox-gw-iceoryx2dds` has a iceoryx Subscriber and a DDS datawriter
1. `iox-gw-dds2iceoryx` has a iceoryx Publisher and a DDS datareader

When running `iox-gw-dds2iceoryx` i get a segmentaion fault with the following message:
```
“./build/iceoryx_dds/iox-gw-dds2…” terminated by signal SIGSEGV (Address boundary error)
```

I was able to trace it to the point where the error occurs:
https://github.com/ApexAI/iceoryx/blob/c1d99922579ab079262b10faebd2ef36a38d2149/iceoryx_dds/source/iceoryx_dds/dds/cyclone_data_reader.cpp#L130
```cpp
bool iox::dds::CycloneDataReader::hasSamples() noexcept
{
    auto samples = m_impl.select().max_samples(1u).state(::dds::sub::status::SampleState::any()).read();
    return samples.length() > 0;
}
```

The purpose of this function is to detect if there are samples available in the DDS reader, that is declared as follows:
https://github.com/ApexAI/iceoryx/blob/iox-%23736-update-cyclonedds-to-idlcxx/iceoryx_dds/include/iceoryx_dds/dds/cyclone_data_reader.hpp#L65
```cpp
::dds::sub::DataReader<Mempool::Chunk> m_impl = ::dds::core::null;
```

I'm not sure if maybe the generated message is not correct or if we maybe misuse the DDS-CXX API here.
Is there maybe a more elegant way to determine if samples have arrived in the datareader?

**Expected result or behaviour:**
Segmentation fault does not occur.

**Conditions where it occurred / Performed steps:**

1. Checkout the above mentioned branch
2. Create in `/etc/iceoryx/` a file called `gateway_config.toml` with the following code:
```toml
[[services]]
service = "Radar"
instance = "FrontLeft"
event = "Counter"
```
3. Build iceoryx with the following command:
```bash
./tools/iceoryx_build_test.sh build-all debug clean
```
4. Open a terminal in iceoryx folder and start roudi with
```bash
./build/iox-roudi
```
5. Create another terminal in iceoryx folder and start the gateway application
```bash
./build/iceoryx_dds/iox-gw-dds2iceoryx
```

If you need more info like the generated message files, let me know.

**Comment by sumanth-nirmal** [comment]
@dkroenke I think I ran into the same issue and tried to fix the cause of the segfaults here #68

**Comment by dkroenke** [comment]
@sumanth-nirmal I can confirm that your bugfix resolves that problem, i will close this issue here and will wait patiently for merging your PR, thanks!

**Comment by k0ekk0ek** [comment]
@dkroenke, @sumanth-nirmal, just for informational purposes: the indicated PR is not really a fix. While porting the API tests to the templated-streaming branch I ran into the same issue. Oddly enough it always happens (only?) when a content filter is applied. @e-hndrks kindly offered to look into it.
