### ISSUE TITLE
IDL-Compiler: Constants cannot be used to declare a sequence

### ISSUE THREAD

**Issue by EttoreVidotto** [eclipse-cyclonedds/cyclonedds-cxx#67]
Hello everyone,
I have a problem with using a previously declared constant to create a sequence. To reproduce the problem, consider the following IDL file:
```idl
module Msg
{
    const long MAX_LENGTH = 10;
    const long MAX_NAMES = 5;

    struct StringSeq 
    {
        long id;
        sequence<string<MAX_LENGTH>, MAX_NAMES> names;
    };
    #pragma keylist StringSeq id
};
```
which should allow me to work with a vector with at most 5 strings of maximal 10 characters. Of course, the idea is to use those constants at several places in the IDL file. Now, I would like to write a message using cyclonedds-cxx. To this end, I just took the helloworld example, I changed the IDL file with mine above and replaced the content of the file publisher.cpp with:
```c++
#include <cstdlib>
#include <iostream>
#include <chrono>
#include <thread>
#include "dds/dds.hpp"
#include "StringSeq.hpp"
using namespace org::eclipse::cyclonedds;
int main() {
    dds::domain::DomainParticipant participant(0);
    dds::topic::Topic<Msg::StringSeq> topic(participant, "StringSeq");
    dds::pub::Publisher publisher(participant);
    dds::pub::DataWriter<Msg::StringSeq> writer(publisher, topic);
    while (writer.publication_matched_status().current_count() == 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(20));
    }
    std::vector<std::string> stringVector{"Signal1", "Signal2", "Signal3"};
    Msg::StringSeq msg(18, stringVector);
    writer.write(msg);
    while (writer.publication_matched_status().current_count() > 0) {
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }
    return EXIT_SUCCESS;
}
```
Compiling the solution results in the error `cannot evaluate <expression> as integer expression`.
I have been using the commit 5ba9629ce606c083f0056adb23218cad8076b962 from the idlcxx branch.

Thank you in advance, any help would be appreciated.
Best regards,
Ettore Vidotto

**Comment by k0ekk0ek** [comment]
Hi @EttoreVidotto! Sorry this went unnoticed for so long. I did a quick test on the *templated-streaming* branch, which is in much better shape than the last time you tried it, especially once #76 is merged, and the IDL compiled without problems. I know it's not quite the answer you're looking for but we try focus on the *templated-streaming* branch as much as possible. If you want to keep using the *idlcxx* branches for now, one workaround would be to use preprocessor defines (the IDL compiler includes a preprocessor).

**Comment by EttoreVidotto** [comment]
Hi Jeroen, thank you very much for your answer. I tried both your suggestions, using the templated-streaming branch and preprocessor defines, and with both methods the problem does not occur anymore.
Thanks again!
