### ISSUE TITLE
Using LoanedSamples invokes deserialization multiple times 

### ISSUE THREAD

**Issue by sumanth-nirmal** [eclipse-cyclonedds/cyclonedds-cxx#70]
### Current Behavior

When using the `LoanedSamples` as described below with the following version of Cyclone DDS
- cyclonedds => [idcxx branch](https://github.com/eclipse-cyclonedds/cyclonedds/tree/idlcxx), commit - [a5db83fe94e9f4afe896e335e69bc5bea741e4d8](https://github.com/eclipse-cyclonedds/cyclonedds/commit/a5db83fe94e9f4afe896e335e69bc5bea741e4d8)
- cyclonedds-cxx => [idlcxx branch](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commits/idlcxx), commit - [e8e09967876fecca97f2eba440d5448c83c8912b](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/commit/e8e09967876fecca97f2eba440d5448c83c8912b)

```cpp
dds::sub::LoanedSamples<DDSType> dds_messages;
dds_messages = m_datareader.select().state(dds::sub::status::DataState::any()).max_samples(1).take();

if (dds_messages.length() > 0U) {
    const auto & it = dds_messages.begin();
    const auto & sample = it->data();
    const auto & sample_info = it->info();
...
# use sample and info
}
```
The same sample is deserialized twice. \
As `ddscxx_serdata` stores the deserialized sample, calling  `getT()` will anyways get the deserialized sample. However, the current code tries to deserialize the sample twice, once [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/e8e09967876fecca97f2eba440d5448c83c8912b/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp#L88) in [`getT()`](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/e8e09967876fecca97f2eba440d5448c83c8912b/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp#L178) which is called from `serdata_from_ser()` and second time [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/e8e09967876fecca97f2eba440d5448c83c8912b/src/ddscxx/include/org/eclipse/cyclonedds/topic/datatopic.hpp#L178) in `serdata_from_ser()`. \
I think this can be optimized to invoke `read_struct()` only once.

### Expected Behaviour

The sample is deserialized only once in the take/read path with `LoanedSamples`.

**Comment by eboasson** [comment]
I'd think the one in `getT()` should suffice, considering that the other one gets the pointer by calling `getT()`. @reicheratwork or @e-hndrks, perhaps you could take a look? I think you both know that code rather well.

**Comment by reicheratwork** [comment]
@sumanth-nirmal @eboasson I have taken up this issue and I think I have a solution for it.

**Comment by k0ekk0ek** [comment]
This has been fixed. Closing the issue.
