### ISSUE TITLE
Questions: concerning documentation and config files

### ISSUE THREAD

**Issue by Kischy** [eclipse-cyclonedds/cyclonedds-cxx#72]
Hi, three quick questions:
- [x] Is it possible to build the doxygen documentation yet?
- [x] Is there an example config file somewhere?
- [x] Is this the right place to ask questions?

**Comment by Kischy** [comment]
I found an example config: I just used this one https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/f00724309b8aec10d400077613ede13a2b418f83/src/ddscxx/tests/config_simple.xml.in

**Comment by k0ekk0ek** [comment]
Hi @Kischy!

1. It should be possible to build the documentation if you pass `-DBUILD_DOCS=on` to CMake in the configuration step. And then use the `docs` (`cmake --build . --target docs`) target to build. That should get you API documentation.
2. The configuration is the same as for *cyclonedds*. To get a quick overview see [options.md](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/docs/manual/options.md). It isn't super user friendly yet, but it does provide descriptions. If you use an editor that supports it (Visual Studio Code with the right plugin), you can use [cyclonedds.xsd](https://github.com/eclipse-cyclonedds/cyclonedds/blob/master/etc/cyclonedds.xsd) to do basic checking. If you're just using Cyclone DDS for the first time and are trying to get a feel for it, then you're probably better of relying on the default configuration for now.
3. Absolutely :slightly_smiling_face:

**Comment by Kischy** [comment]
@k0ekk0ek Thank you

**Comment by k0ekk0ek** [comment]
Whether you use `ON` or `on` doesn't really matter, but you may have to generate a fresh set of makefiles. The command I used to generate the build system is (makefiles): `cmake -DCMAKE_BUILD_TYPE=Debug -DBUILD_TESTING=On -DBUILD_EXAMPLES=On -DCMAKE_INSTALL_PREFIX=install -DCMAKE_PREFIX_PATH=<cyclonedds-build-directory>/install -DSANITIZER=address -DANALYZER=on -DBUILD_DOCS=on ..`. To build the documentation I issued: `cmake --build . --target docs`. The documentation then shows up in `<build-directory>/docs/docs`. Those are the API docs merged with what will eventually be a nice guide. Doxygen documentation is generated in `<build-directory>/src/ddscxx/html/index.html`. Both aren't especially user-friendly at the moment. The API documentation can also be downloaded from the OMG (https://www.omg.org/spec/DDS-PSM-Cxx/About-DDS-PSM-Cxx/). *ISO/IEC C++ DDS PSM FTF 2 spec api-docs* is what you're looking for on that page.

**Comment by Kischy** [comment]
@k0ekk0ek Thank you.
