### ISSUE TITLE
prevent_callbacks() function aborts during cleanup

### ISSUE THREAD

**Issue by sumanth-nirmal** [eclipse-cyclonedds/cyclonedds-cxx#81]
## Required information

**Operating system:**
Ubuntu 18.04 LTS

**Cyclone Version**
- cyclonedds - https://github.com/eclipse-cyclonedds/cyclonedds/releases/tag/0.8.0beta1
- cyclonedds-cxx - https://github.com/eclipse-cyclonedds/cyclonedds-cxx/releases/tag/0.1.0beta1

**Observed result or behaviour:**

In some very specific scenario's during cleanup, in function `org::eclipse::cyclonedds::core::EntityDelegate::prevent_callbacks()` the check `assert(false)` [here](https://github.com/eclipse-cyclonedds/cyclonedds-cxx/blob/554bccc1fe276643eb4ad9ec309c2b09b0dec79f/src/ddscxx/src/org/eclipse/cyclonedds/core/EntityDelegate.cpp#L255) fails causing the application to abort with out exiting cleanly. 

**Expected result or behaviour:**

The usage of C++ API shouldn't lead to this abort in the runtime, or the API usage should be clearly specified with unhandled scenarios.

**Conditions where it occurred / Performed steps:**

As a workaround, during the cleanup I un-register the listener and then call close on the other DDS entities as shown below, which seems to not cause the error.

```
    // unregister the listener
    m_reader.listener(nullptr, dds::core::status::StatusMask::none());
    // close the guard condition
    m_guard_condition.close();
    // close the data reader
    m_reader->close();
```

**Comment by k0ekk0ek** [comment]
This has been fixed in my PR on the templated-streaming branch (#79). Can you try cherry-picking commit `b06c36681965a2d8f05416db5351aea79d59ee1f` from that branch?

**Comment by k0ekk0ek** [comment]
@sumanth-nirmal, I'm going to assume this has indeed been fixed. Closing the issue.
