### ISSUE TITLE
Question: How can I redirect an error message?

### ISSUE THREAD

**Issue by Kischy** [eclipse-cyclonedds/cyclonedds-cxx#82]
I am wondering: How I can redirect an error message like this one `1621242890.222409 [0]      20352: can't open configuration file config_simple.xml`. I would prefer a way to access the message in code. Is there an easy way to to this?

**Comment by k0ekk0ek** [comment]
Hi @Kischy. That's totally possible. `dds_set_log_sink` and `dds_set_trace_sink` are the functions you're looking for.

**Comment by Kischy** [comment]
Thank you!
